// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
// AUTOGENERATED by tools/codegen/emit_c.py — do not edit.
// Regenerate via:  python -m tools.codegen.codegen flakes --backend c-source

#include "whiteout_flakes.h"

#include <cstring>
#include <new>
#include <span>
#include <string>
#include <vector>

#include <whiteout/flakes/types.h>
#include <whiteout/flakes/gfx_types.h>
#include <whiteout/flakes/enums.h>
#include <whiteout/flakes/shadow_params.h>
#include <whiteout/flakes/display.h>
#include <whiteout/flakes/util/replaceable_paths.h>
#include <whiteout/flakes/views.h>
#include <whiteout/flakes/actor_view.h>
#include <whiteout/flakes/renderer.h>
#include <whiteout/flakes/storage_browser.h>

namespace { using namespace whiteout; }

namespace {

// `whiteout::u8` is `std::uint8_t`, so a single overload suffices. We use
// the project's type so the reinterpret_cast is a no-op everywhere the
// codegen runs.
inline whiteout_Bytes wrapBytes(std::vector<whiteout::u8>&& v) {
    auto* owned = new std::vector<whiteout::u8>(std::move(v));
    return { reinterpret_cast<const uint8_t*>(owned->data()), owned->size(), owned };
}

inline whiteout_Bytes emptyBytes() {
    return { nullptr, 0, nullptr };
}

inline whiteout_CString wrapCString(std::string&& s) {
    auto* owned = new std::string(std::move(s));
    return { owned->c_str(), owned->size(), owned };
}

inline whiteout_CString emptyCString() {
    return { nullptr, 0, nullptr };
}

} // anonymous

size_t whiteout_flakes_StringList_size(const whiteout_StringList* self) {
    return reinterpret_cast<const std::vector<std::string>*>(self)->size();
}

whiteout_CString whiteout_flakes_StringList_at(whiteout_StringList* self, size_t index) {
    auto* v = reinterpret_cast<std::vector<std::string>*>(self);
    if (index >= v->size()) return emptyCString();
    const std::string& s = (*v)[index];
    return whiteout_CString{ s.c_str(), s.size(), nullptr };
}

void whiteout_flakes_StringList_delete(whiteout_StringList* self) {
    delete reinterpret_cast<std::vector<std::string>*>(self);
}

size_t whiteout_flakes_SequenceInfoList_size(const whiteout_SequenceInfoList* self) {
    return reinterpret_cast<const std::vector<whiteout::flakes::SequenceInfo>*>(self)->size();
}

struct whiteout_SequenceInfo* whiteout_flakes_SequenceInfoList_at(whiteout_SequenceInfoList* self, size_t index) {
    auto* v = reinterpret_cast<std::vector<whiteout::flakes::SequenceInfo>*>(self);
    return reinterpret_cast<struct whiteout_SequenceInfo*>(&(*v)[index]);
}

void whiteout_flakes_SequenceInfoList_delete(whiteout_SequenceInfoList* self) {
    delete reinterpret_cast<std::vector<whiteout::flakes::SequenceInfo>*>(self);
}

size_t whiteout_flakes_CameraPresetList_size(const whiteout_CameraPresetList* self) {
    return reinterpret_cast<const std::vector<whiteout::flakes::CameraPreset>*>(self)->size();
}

struct whiteout_CameraPreset* whiteout_flakes_CameraPresetList_at(whiteout_CameraPresetList* self, size_t index) {
    auto* v = reinterpret_cast<std::vector<whiteout::flakes::CameraPreset>*>(self);
    return reinterpret_cast<struct whiteout_CameraPreset*>(&(*v)[index]);
}

void whiteout_flakes_CameraPresetList_delete(whiteout_CameraPresetList* self) {
    delete reinterpret_cast<std::vector<whiteout::flakes::CameraPreset>*>(self);
}
// ── FlakesRect ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesRect* whiteout_flakes_FlakesRect_new(void) {
    return reinterpret_cast<whiteout_FlakesRect*>(new whiteout::flakes::Rect());
}

void whiteout_flakes_FlakesRect_delete(whiteout_FlakesRect* self) {
    delete reinterpret_cast<whiteout::flakes::Rect*>(self);
}

int32_t whiteout_flakes_FlakesRect_get_left(const whiteout_FlakesRect* self) {
    return reinterpret_cast<const whiteout::flakes::Rect*>(self)->left;
}

void whiteout_flakes_FlakesRect_set_left(whiteout_FlakesRect* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::Rect*>(self)->left = value;
}

int32_t whiteout_flakes_FlakesRect_get_top(const whiteout_FlakesRect* self) {
    return reinterpret_cast<const whiteout::flakes::Rect*>(self)->top;
}

void whiteout_flakes_FlakesRect_set_top(whiteout_FlakesRect* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::Rect*>(self)->top = value;
}

int32_t whiteout_flakes_FlakesRect_get_right(const whiteout_FlakesRect* self) {
    return reinterpret_cast<const whiteout::flakes::Rect*>(self)->right;
}

void whiteout_flakes_FlakesRect_set_right(whiteout_FlakesRect* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::Rect*>(self)->right = value;
}

int32_t whiteout_flakes_FlakesRect_get_bottom(const whiteout_FlakesRect* self) {
    return reinterpret_cast<const whiteout::flakes::Rect*>(self)->bottom;
}

void whiteout_flakes_FlakesRect_set_bottom(whiteout_FlakesRect* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::Rect*>(self)->bottom = value;
}

} // extern "C"

// ── FlakesShadowParams ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesShadowParams* whiteout_flakes_FlakesShadowParams_new(void) {
    return reinterpret_cast<whiteout_FlakesShadowParams*>(new whiteout::flakes::ShadowParams());
}

void whiteout_flakes_FlakesShadowParams_delete(whiteout_FlakesShadowParams* self) {
    delete reinterpret_cast<whiteout::flakes::ShadowParams*>(self);
}

int32_t whiteout_flakes_FlakesShadowParams_get_cascadeCount(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->cascadeCount;
}

void whiteout_flakes_FlakesShadowParams_set_cascadeCount(whiteout_FlakesShadowParams* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->cascadeCount = value;
}

int32_t whiteout_flakes_FlakesShadowParams_get_cascadeResolution(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->cascadeResolution;
}

void whiteout_flakes_FlakesShadowParams_set_cascadeResolution(whiteout_FlakesShadowParams* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->cascadeResolution = value;
}

float whiteout_flakes_FlakesShadowParams_get_casterHeight(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->casterHeight;
}

void whiteout_flakes_FlakesShadowParams_set_casterHeight(whiteout_FlakesShadowParams* self, float value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->casterHeight = value;
}

float whiteout_flakes_FlakesShadowParams_get_lambdaSplit(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->lambdaSplit;
}

void whiteout_flakes_FlakesShadowParams_set_lambdaSplit(whiteout_FlakesShadowParams* self, float value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->lambdaSplit = value;
}

int32_t whiteout_flakes_FlakesShadowParams_get_depthBias(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->depthBias;
}

void whiteout_flakes_FlakesShadowParams_set_depthBias(whiteout_FlakesShadowParams* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->depthBias = value;
}

float whiteout_flakes_FlakesShadowParams_get_slopeScaledBias(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->slopeScaledBias;
}

void whiteout_flakes_FlakesShadowParams_set_slopeScaledBias(whiteout_FlakesShadowParams* self, float value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->slopeScaledBias = value;
}

float whiteout_flakes_FlakesShadowParams_get_depthBiasClamp(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->depthBiasClamp;
}

void whiteout_flakes_FlakesShadowParams_set_depthBiasClamp(whiteout_FlakesShadowParams* self, float value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->depthBiasClamp = value;
}

int32_t whiteout_flakes_FlakesShadowParams_get_texelSnap(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->texelSnap;
}

void whiteout_flakes_FlakesShadowParams_set_texelSnap(whiteout_FlakesShadowParams* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->texelSnap = value;
}

int32_t whiteout_flakes_FlakesShadowParams_get_enabled(const whiteout_FlakesShadowParams* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowParams*>(self)->enabled;
}

void whiteout_flakes_FlakesShadowParams_set_enabled(whiteout_FlakesShadowParams* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::ShadowParams*>(self)->enabled = value;
}

} // extern "C"

// ── FlakesDisplayFlags ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesDisplayFlags* whiteout_flakes_FlakesDisplayFlags_new(void) {
    return reinterpret_cast<whiteout_FlakesDisplayFlags*>(new whiteout::flakes::DisplayFlags());
}

void whiteout_flakes_FlakesDisplayFlags_delete(whiteout_FlakesDisplayFlags* self) {
    delete reinterpret_cast<whiteout::flakes::DisplayFlags*>(self);
}

int32_t whiteout_flakes_FlakesDisplayFlags_get_showGrid(const whiteout_FlakesDisplayFlags* self) {
    return reinterpret_cast<const whiteout::flakes::DisplayFlags*>(self)->showGrid;
}

void whiteout_flakes_FlakesDisplayFlags_set_showGrid(whiteout_FlakesDisplayFlags* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::DisplayFlags*>(self)->showGrid = value;
}

int32_t whiteout_flakes_FlakesDisplayFlags_get_showParticles(const whiteout_FlakesDisplayFlags* self) {
    return reinterpret_cast<const whiteout::flakes::DisplayFlags*>(self)->showParticles;
}

void whiteout_flakes_FlakesDisplayFlags_set_showParticles(whiteout_FlakesDisplayFlags* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::DisplayFlags*>(self)->showParticles = value;
}

int32_t whiteout_flakes_FlakesDisplayFlags_get_showRibbons(const whiteout_FlakesDisplayFlags* self) {
    return reinterpret_cast<const whiteout::flakes::DisplayFlags*>(self)->showRibbons;
}

void whiteout_flakes_FlakesDisplayFlags_set_showRibbons(whiteout_FlakesDisplayFlags* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::DisplayFlags*>(self)->showRibbons = value;
}

int32_t whiteout_flakes_FlakesDisplayFlags_get_showCollisions(const whiteout_FlakesDisplayFlags* self) {
    return reinterpret_cast<const whiteout::flakes::DisplayFlags*>(self)->showCollisions;
}

void whiteout_flakes_FlakesDisplayFlags_set_showCollisions(whiteout_FlakesDisplayFlags* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::DisplayFlags*>(self)->showCollisions = value;
}

int32_t whiteout_flakes_FlakesDisplayFlags_get_showLights(const whiteout_FlakesDisplayFlags* self) {
    return reinterpret_cast<const whiteout::flakes::DisplayFlags*>(self)->showLights;
}

void whiteout_flakes_FlakesDisplayFlags_set_showLights(whiteout_FlakesDisplayFlags* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::DisplayFlags*>(self)->showLights = value;
}

int32_t whiteout_flakes_FlakesDisplayFlags_get_showEvents(const whiteout_FlakesDisplayFlags* self) {
    return reinterpret_cast<const whiteout::flakes::DisplayFlags*>(self)->showEvents;
}

void whiteout_flakes_FlakesDisplayFlags_set_showEvents(whiteout_FlakesDisplayFlags* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::DisplayFlags*>(self)->showEvents = value;
}

int32_t whiteout_flakes_FlakesDisplayFlags_get_renderMode(const whiteout_FlakesDisplayFlags* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::DisplayFlags*>(self)->renderMode);
}

void whiteout_flakes_FlakesDisplayFlags_set_renderMode(whiteout_FlakesDisplayFlags* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::DisplayFlags*>(self)->renderMode = static_cast<whiteout::flakes::RenderMode>(value);
}

} // extern "C"

// ── FlakesFrameStats ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesFrameStats* whiteout_flakes_FlakesFrameStats_new(void) {
    return reinterpret_cast<whiteout_FlakesFrameStats*>(new whiteout::flakes::FrameStats());
}

void whiteout_flakes_FlakesFrameStats_delete(whiteout_FlakesFrameStats* self) {
    delete reinterpret_cast<whiteout::flakes::FrameStats*>(self);
}

int32_t whiteout_flakes_FlakesFrameStats_get_geosets(const whiteout_FlakesFrameStats* self) {
    return reinterpret_cast<const whiteout::flakes::FrameStats*>(self)->geosets;
}

void whiteout_flakes_FlakesFrameStats_set_geosets(whiteout_FlakesFrameStats* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::FrameStats*>(self)->geosets = value;
}

int32_t whiteout_flakes_FlakesFrameStats_get_textures(const whiteout_FlakesFrameStats* self) {
    return reinterpret_cast<const whiteout::flakes::FrameStats*>(self)->textures;
}

void whiteout_flakes_FlakesFrameStats_set_textures(whiteout_FlakesFrameStats* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::FrameStats*>(self)->textures = value;
}

int32_t whiteout_flakes_FlakesFrameStats_get_nodes(const whiteout_FlakesFrameStats* self) {
    return reinterpret_cast<const whiteout::flakes::FrameStats*>(self)->nodes;
}

void whiteout_flakes_FlakesFrameStats_set_nodes(whiteout_FlakesFrameStats* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::FrameStats*>(self)->nodes = value;
}

int32_t whiteout_flakes_FlakesFrameStats_get_particles(const whiteout_FlakesFrameStats* self) {
    return reinterpret_cast<const whiteout::flakes::FrameStats*>(self)->particles;
}

void whiteout_flakes_FlakesFrameStats_set_particles(whiteout_FlakesFrameStats* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::FrameStats*>(self)->particles = value;
}

int32_t whiteout_flakes_FlakesFrameStats_get_segments(const whiteout_FlakesFrameStats* self) {
    return reinterpret_cast<const whiteout::flakes::FrameStats*>(self)->segments;
}

void whiteout_flakes_FlakesFrameStats_set_segments(whiteout_FlakesFrameStats* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::FrameStats*>(self)->segments = value;
}

int32_t whiteout_flakes_FlakesFrameStats_get_cornParticles(const whiteout_FlakesFrameStats* self) {
    return reinterpret_cast<const whiteout::flakes::FrameStats*>(self)->cornParticles;
}

void whiteout_flakes_FlakesFrameStats_set_cornParticles(whiteout_FlakesFrameStats* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::FrameStats*>(self)->cornParticles = value;
}

} // extern "C"

// ── FlakesCameraPreset ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesCameraPreset* whiteout_flakes_FlakesCameraPreset_new(void) {
    return reinterpret_cast<whiteout_FlakesCameraPreset*>(new whiteout::flakes::CameraPreset());
}

void whiteout_flakes_FlakesCameraPreset_delete(whiteout_FlakesCameraPreset* self) {
    delete reinterpret_cast<whiteout::flakes::CameraPreset*>(self);
}

whiteout_CString whiteout_flakes_FlakesCameraPreset_get_name(const whiteout_FlakesCameraPreset* self) {
    auto* __owned = new std::string(reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->name);
    return whiteout_CString{ __owned->c_str(), __owned->size(), __owned };
}

void whiteout_flakes_FlakesCameraPreset_set_name(whiteout_FlakesCameraPreset* self, const char* value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->name = (value ? value : "");
}

int32_t whiteout_flakes_FlakesCameraPreset_get_isLive(const whiteout_FlakesCameraPreset* self) {
    return reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->isLive;
}

void whiteout_flakes_FlakesCameraPreset_set_isLive(whiteout_FlakesCameraPreset* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->isLive = value;
}

float whiteout_flakes_FlakesCameraPreset_get_fovDiagonal(const whiteout_FlakesCameraPreset* self) {
    return reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->fovDiagonal;
}

void whiteout_flakes_FlakesCameraPreset_set_fovDiagonal(whiteout_FlakesCameraPreset* self, float value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->fovDiagonal = value;
}

float whiteout_flakes_FlakesCameraPreset_get_zNear(const whiteout_FlakesCameraPreset* self) {
    return reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->zNear;
}

void whiteout_flakes_FlakesCameraPreset_set_zNear(whiteout_FlakesCameraPreset* self, float value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->zNear = value;
}

float whiteout_flakes_FlakesCameraPreset_get_zFar(const whiteout_FlakesCameraPreset* self) {
    return reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->zFar;
}

void whiteout_flakes_FlakesCameraPreset_set_zFar(whiteout_FlakesCameraPreset* self, float value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->zFar = value;
}

float whiteout_flakes_FlakesCameraPreset_get_staticRoll(const whiteout_FlakesCameraPreset* self) {
    return reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->staticRoll;
}

void whiteout_flakes_FlakesCameraPreset_set_staticRoll(whiteout_FlakesCameraPreset* self, float value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->staticRoll = value;
}

float whiteout_flakes_FlakesCameraPreset_get_pitch(const whiteout_FlakesCameraPreset* self) {
    return reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->pitch;
}

void whiteout_flakes_FlakesCameraPreset_set_pitch(whiteout_FlakesCameraPreset* self, float value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->pitch = value;
}

float whiteout_flakes_FlakesCameraPreset_get_yaw(const whiteout_FlakesCameraPreset* self) {
    return reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->yaw;
}

void whiteout_flakes_FlakesCameraPreset_set_yaw(whiteout_FlakesCameraPreset* self, float value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->yaw = value;
}

float whiteout_flakes_FlakesCameraPreset_get_distance(const whiteout_FlakesCameraPreset* self) {
    return reinterpret_cast<const whiteout::flakes::CameraPreset*>(self)->distance;
}

void whiteout_flakes_FlakesCameraPreset_set_distance(whiteout_FlakesCameraPreset* self, float value) {
    reinterpret_cast<whiteout::flakes::CameraPreset*>(self)->distance = value;
}

} // extern "C"

// ── FlakesSequenceInfo ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesSequenceInfo* whiteout_flakes_FlakesSequenceInfo_new(void) {
    return reinterpret_cast<whiteout_FlakesSequenceInfo*>(new whiteout::flakes::SequenceInfo());
}

void whiteout_flakes_FlakesSequenceInfo_delete(whiteout_FlakesSequenceInfo* self) {
    delete reinterpret_cast<whiteout::flakes::SequenceInfo*>(self);
}

whiteout_CString whiteout_flakes_FlakesSequenceInfo_get_name(const whiteout_FlakesSequenceInfo* self) {
    auto* __owned = new std::string(reinterpret_cast<const whiteout::flakes::SequenceInfo*>(self)->name);
    return whiteout_CString{ __owned->c_str(), __owned->size(), __owned };
}

void whiteout_flakes_FlakesSequenceInfo_set_name(whiteout_FlakesSequenceInfo* self, const char* value) {
    reinterpret_cast<whiteout::flakes::SequenceInfo*>(self)->name = (value ? value : "");
}

int32_t whiteout_flakes_FlakesSequenceInfo_get_startMs(const whiteout_FlakesSequenceInfo* self) {
    return reinterpret_cast<const whiteout::flakes::SequenceInfo*>(self)->startMs;
}

void whiteout_flakes_FlakesSequenceInfo_set_startMs(whiteout_FlakesSequenceInfo* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::SequenceInfo*>(self)->startMs = value;
}

int32_t whiteout_flakes_FlakesSequenceInfo_get_endMs(const whiteout_FlakesSequenceInfo* self) {
    return reinterpret_cast<const whiteout::flakes::SequenceInfo*>(self)->endMs;
}

void whiteout_flakes_FlakesSequenceInfo_set_endMs(whiteout_FlakesSequenceInfo* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::SequenceInfo*>(self)->endMs = value;
}

float whiteout_flakes_FlakesSequenceInfo_get_moveSpeed(const whiteout_FlakesSequenceInfo* self) {
    return reinterpret_cast<const whiteout::flakes::SequenceInfo*>(self)->moveSpeed;
}

void whiteout_flakes_FlakesSequenceInfo_set_moveSpeed(whiteout_FlakesSequenceInfo* self, float value) {
    reinterpret_cast<whiteout::flakes::SequenceInfo*>(self)->moveSpeed = value;
}

float whiteout_flakes_FlakesSequenceInfo_get_rarity(const whiteout_FlakesSequenceInfo* self) {
    return reinterpret_cast<const whiteout::flakes::SequenceInfo*>(self)->rarity;
}

void whiteout_flakes_FlakesSequenceInfo_set_rarity(whiteout_FlakesSequenceInfo* self, float value) {
    reinterpret_cast<whiteout::flakes::SequenceInfo*>(self)->rarity = value;
}

int32_t whiteout_flakes_FlakesSequenceInfo_get_nonLooping(const whiteout_FlakesSequenceInfo* self) {
    return reinterpret_cast<const whiteout::flakes::SequenceInfo*>(self)->nonLooping;
}

void whiteout_flakes_FlakesSequenceInfo_set_nonLooping(whiteout_FlakesSequenceInfo* self, int32_t value) {
    reinterpret_cast<whiteout::flakes::SequenceInfo*>(self)->nonLooping = value;
}

} // extern "C"

// ── FlakesPipelineView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesPipelineView_delete(whiteout_FlakesPipelineView* self) {
    delete reinterpret_cast<whiteout::flakes::PipelineView*>(self);
}

void whiteout_flakes_FlakesPipelineView_InitDevice(whiteout_FlakesPipelineView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::PipelineView*>(self)->InitDevice(static_cast<whiteout::flakes::gfx::GfxApi>(arg));
}

int32_t whiteout_flakes_FlakesPipelineView_IsDeviceReady(const whiteout_FlakesPipelineView* self) {
    return reinterpret_cast<const whiteout::flakes::PipelineView*>(self)->IsDeviceReady();
}

uint32_t whiteout_flakes_FlakesPipelineView_CreateOffscreenTarget(whiteout_FlakesPipelineView* self, int32_t width, int32_t height) {
    return reinterpret_cast<whiteout::flakes::PipelineView*>(self)->CreateOffscreenTarget(width, height);
}

void whiteout_flakes_FlakesPipelineView_DestroyTarget(whiteout_FlakesPipelineView* self, uint32_t arg) {
    reinterpret_cast<whiteout::flakes::PipelineView*>(self)->DestroyTarget(arg);
}

void whiteout_flakes_FlakesPipelineView_SetPrimaryTarget(whiteout_FlakesPipelineView* self, uint32_t arg) {
    reinterpret_cast<whiteout::flakes::PipelineView*>(self)->SetPrimaryTarget(arg);
}

void whiteout_flakes_FlakesPipelineView_ResizePrimaryTarget(whiteout_FlakesPipelineView* self, int32_t width, int32_t height) {
    reinterpret_cast<whiteout::flakes::PipelineView*>(self)->ResizePrimaryTarget(width, height);
}

void whiteout_flakes_FlakesPipelineView_RenderFrame(whiteout_FlakesPipelineView* self, uint32_t t) {
    reinterpret_cast<whiteout::flakes::PipelineView*>(self)->RenderFrame(t);
}

void whiteout_flakes_FlakesPipelineView_RenderViewport(whiteout_FlakesPipelineView* self, uint32_t t, uint32_t camera) {
    reinterpret_cast<whiteout::flakes::PipelineView*>(self)->RenderViewport(t, camera);
}

void whiteout_flakes_FlakesPipelineView_Present(whiteout_FlakesPipelineView* self, uint32_t t) {
    reinterpret_cast<whiteout::flakes::PipelineView*>(self)->Present(t);
}

void whiteout_flakes_FlakesPipelineView_Shutdown(whiteout_FlakesPipelineView* self) {
    reinterpret_cast<whiteout::flakes::PipelineView*>(self)->Shutdown();
}

struct whiteout_FlakesFrameStats* whiteout_flakes_FlakesPipelineView_FrameStats(const whiteout_FlakesPipelineView* self) {
    return reinterpret_cast<struct whiteout_FlakesFrameStats*>(
        new whiteout::flakes::FrameStats(reinterpret_cast<const whiteout::flakes::PipelineView*>(self)->GetFrameStats()));
}

uint64_t whiteout_flakes_FlakesPipelineView_LiveGpuBytes(const whiteout_FlakesPipelineView* self) {
    return reinterpret_cast<const whiteout::flakes::PipelineView*>(self)->LiveGpuBytes();
}

} // extern "C"

// ── FlakesSceneView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesSceneView_delete(whiteout_FlakesSceneView* self) {
    delete reinterpret_cast<whiteout::flakes::SceneView*>(self);
}

int32_t whiteout_flakes_FlakesSceneView_AnimationTimeMs(const whiteout_FlakesSceneView* self) {
    return reinterpret_cast<const whiteout::flakes::SceneView*>(self)->AnimationTimeMs();
}

void whiteout_flakes_FlakesSceneView_SetAnimationTimeMs(whiteout_FlakesSceneView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::SceneView*>(self)->SetAnimationTimeMs(arg);
}

void whiteout_flakes_FlakesSceneView_Update(whiteout_FlakesSceneView* self, float dt) {
    reinterpret_cast<whiteout::flakes::SceneView*>(self)->Update(dt);
}

void whiteout_flakes_FlakesSceneView_SetCascInstallPath(whiteout_FlakesSceneView* self, const char* root) {
    reinterpret_cast<whiteout::flakes::SceneView*>(self)->SetCascInstallPath(std::string(root ? root : ""));
}

void whiteout_flakes_FlakesSceneView_SetHdMode(whiteout_FlakesSceneView* self, int32_t enabled) {
    reinterpret_cast<whiteout::flakes::SceneView*>(self)->SetHdMode(enabled);
}

} // extern "C"

// ── FlakesCameraView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesCameraView_delete(whiteout_FlakesCameraView* self) {
    delete reinterpret_cast<whiteout::flakes::CameraView*>(self);
}

void whiteout_flakes_FlakesCameraView_Reset(whiteout_FlakesCameraView* self) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->Reset();
}

void whiteout_flakes_FlakesCameraView_SetPitch(whiteout_FlakesCameraView* self, float arg) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->SetPitch(arg);
}

void whiteout_flakes_FlakesCameraView_SetYaw(whiteout_FlakesCameraView* self, float arg) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->SetYaw(arg);
}

void whiteout_flakes_FlakesCameraView_SetDistance(whiteout_FlakesCameraView* self, float arg) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->SetDistance(arg);
}

void whiteout_flakes_FlakesCameraView_SetTarget(whiteout_FlakesCameraView* self, float x, float y, float z) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->SetTarget(x, y, z);
}

void whiteout_flakes_FlakesCameraView_Rotate(whiteout_FlakesCameraView* self, int32_t dx, int32_t dy) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->Rotate(dx, dy);
}

void whiteout_flakes_FlakesCameraView_Pan(whiteout_FlakesCameraView* self, int32_t dx, int32_t dy) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->Pan(dx, dy);
}

void whiteout_flakes_FlakesCameraView_Zoom(whiteout_FlakesCameraView* self, int32_t wheelDelta) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->Zoom(wheelDelta);
}

void whiteout_flakes_FlakesCameraView_ZoomSmooth(whiteout_FlakesCameraView* self, float factor) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->ZoomSmooth(factor);
}

void whiteout_flakes_FlakesCameraView_SetOrbitalMode(whiteout_FlakesCameraView* self) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->SetOrbitalMode();
}

void whiteout_flakes_FlakesCameraView_SetFovDiagonal(whiteout_FlakesCameraView* self, float arg) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->SetFovDiagonal(arg);
}

void whiteout_flakes_FlakesCameraView_SetClip(whiteout_FlakesCameraView* self, float nz, float fz) {
    reinterpret_cast<whiteout::flakes::CameraView*>(self)->SetClip(nz, fz);
}

int32_t whiteout_flakes_FlakesCameraView_Mode(const whiteout_FlakesCameraView* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::CameraView*>(self)->GetMode());
}

float whiteout_flakes_FlakesCameraView_Distance(const whiteout_FlakesCameraView* self) {
    return reinterpret_cast<const whiteout::flakes::CameraView*>(self)->GetDistance();
}

} // extern "C"

// ── FlakesSettingsView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesSettingsView_delete(whiteout_FlakesSettingsView* self) {
    delete reinterpret_cast<whiteout::flakes::SettingsView*>(self);
}

struct whiteout_FlakesDisplayFlags* whiteout_flakes_FlakesSettingsView_DisplayFlags(const whiteout_FlakesSettingsView* self) {
    return reinterpret_cast<struct whiteout_FlakesDisplayFlags*>(
        new whiteout::flakes::DisplayFlags(reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->GetDisplayFlags()));
}

void whiteout_flakes_FlakesSettingsView_SetDisplayFlags(whiteout_FlakesSettingsView* self, struct whiteout_FlakesDisplayFlags* arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetDisplayFlags(*reinterpret_cast<const whiteout::flakes::DisplayFlags*>(arg));
}

int32_t whiteout_flakes_FlakesSettingsView_ConsumeRenderModeDirty(whiteout_FlakesSettingsView* self) {
    return reinterpret_cast<whiteout::flakes::SettingsView*>(self)->ConsumeRenderModeDirty();
}

int32_t whiteout_flakes_FlakesSettingsView_LightingMode(const whiteout_FlakesSettingsView* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->GetLightingMode());
}

void whiteout_flakes_FlakesSettingsView_SetLightingMode(whiteout_FlakesSettingsView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetLightingMode(static_cast<whiteout::flakes::LightingMode>(arg));
}

uint32_t whiteout_flakes_FlakesSettingsView_BackgroundColorRaw(const whiteout_FlakesSettingsView* self) {
    return reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->BackgroundColorRaw();
}

void whiteout_flakes_FlakesSettingsView_SetBackgroundColor(whiteout_FlakesSettingsView* self, uint8_t r, uint8_t g, uint8_t b) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetBackgroundColor(r, g, b);
}

float whiteout_flakes_FlakesSettingsView_TonemapExposure(const whiteout_FlakesSettingsView* self) {
    return reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->GetTonemapExposure();
}

void whiteout_flakes_FlakesSettingsView_SetTonemapExposure(whiteout_FlakesSettingsView* self, float arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetTonemapExposure(arg);
}

int32_t whiteout_flakes_FlakesSettingsView_BloomEnabled(const whiteout_FlakesSettingsView* self) {
    return reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->GetBloomEnabled();
}

void whiteout_flakes_FlakesSettingsView_SetBloomEnabled(whiteout_FlakesSettingsView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetBloomEnabled(arg);
}

int32_t whiteout_flakes_FlakesSettingsView_IblMode(const whiteout_FlakesSettingsView* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->GetIblMode());
}

void whiteout_flakes_FlakesSettingsView_SetIblMode(whiteout_FlakesSettingsView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetIblMode(static_cast<whiteout::flakes::IblMode>(arg));
}

int32_t whiteout_flakes_FlakesSettingsView_HdDebugMode(const whiteout_FlakesSettingsView* self) {
    return reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->HdDebugMode();
}

void whiteout_flakes_FlakesSettingsView_SetHdDebugMode(whiteout_FlakesSettingsView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetHdDebugMode(arg);
}

uint32_t whiteout_flakes_FlakesSettingsView_AoQuality(const whiteout_FlakesSettingsView* self) {
    return reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->AoQuality();
}

void whiteout_flakes_FlakesSettingsView_SetAoQuality(whiteout_FlakesSettingsView* self, uint32_t arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetAoQuality(arg);
}

int32_t whiteout_flakes_FlakesSettingsView_LodOverride(const whiteout_FlakesSettingsView* self) {
    return reinterpret_cast<const whiteout::flakes::SettingsView*>(self)->LodOverride();
}

void whiteout_flakes_FlakesSettingsView_SetLodOverride(whiteout_FlakesSettingsView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetLodOverride(arg);
}

void whiteout_flakes_FlakesSettingsView_SetRenderMode(whiteout_FlakesSettingsView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::SettingsView*>(self)->SetRenderMode(static_cast<whiteout::flakes::RenderMode>(arg));
}

} // extern "C"

// ── FlakesLoaderView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesLoaderView_delete(whiteout_FlakesLoaderView* self) {
    delete reinterpret_cast<whiteout::flakes::LoaderView*>(self);
}

uint32_t whiteout_flakes_FlakesLoaderView_SpawnUnit(whiteout_FlakesLoaderView* self, const char* path) {
    return reinterpret_cast<whiteout::flakes::LoaderView*>(self)->SpawnUnit(std::string(path ? path : ""));
}

uint32_t whiteout_flakes_FlakesLoaderView_SpawnEffect(whiteout_FlakesLoaderView* self, const char* path) {
    return reinterpret_cast<whiteout::flakes::LoaderView*>(self)->SpawnEffect(std::string(path ? path : ""));
}

void whiteout_flakes_FlakesLoaderView_RequestClearAll(whiteout_FlakesLoaderView* self) {
    reinterpret_cast<whiteout::flakes::LoaderView*>(self)->RequestClearAll();
}

void whiteout_flakes_FlakesLoaderView_Destroy(whiteout_FlakesLoaderView* self, uint32_t handle) {
    reinterpret_cast<whiteout::flakes::LoaderView*>(self)->Destroy(handle);
}

} // extern "C"

// ── FlakesAssetsView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesAssetsView_delete(whiteout_FlakesAssetsView* self) {
    delete reinterpret_cast<whiteout::flakes::AssetsView*>(self);
}

struct whiteout_FlakesAssetsViewStats* whiteout_flakes_FlakesAssetsView_Stats(const whiteout_FlakesAssetsView* self) {
    return reinterpret_cast<struct whiteout_FlakesAssetsViewStats*>(
        new whiteout::flakes::AssetsView::Stats(reinterpret_cast<const whiteout::flakes::AssetsView*>(self)->GetStats()));
}

void whiteout_flakes_FlakesAssetsView_PrefetchEventAssets(whiteout_FlakesAssetsView* self) {
    reinterpret_cast<whiteout::flakes::AssetsView*>(self)->PrefetchEventAssets();
}

void whiteout_flakes_FlakesAssetsView_PrefetchEventAssetsForActor(whiteout_FlakesAssetsView* self, uint32_t actor) {
    reinterpret_cast<whiteout::flakes::AssetsView*>(self)->PrefetchEventAssetsForActor(actor);
}

} // extern "C"

// ── FlakesAssetsViewStats ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesAssetsViewStats* whiteout_flakes_FlakesAssetsViewStats_new(void) {
    return reinterpret_cast<whiteout_FlakesAssetsViewStats*>(new whiteout::flakes::AssetsView::Stats());
}

void whiteout_flakes_FlakesAssetsViewStats_delete(whiteout_FlakesAssetsViewStats* self) {
    delete reinterpret_cast<whiteout::flakes::AssetsView::Stats*>(self);
}

uint64_t whiteout_flakes_FlakesAssetsViewStats_get_liveSlots(const whiteout_FlakesAssetsViewStats* self) {
    return reinterpret_cast<const whiteout::flakes::AssetsView::Stats*>(self)->liveSlots;
}

void whiteout_flakes_FlakesAssetsViewStats_set_liveSlots(whiteout_FlakesAssetsViewStats* self, uint64_t value) {
    reinterpret_cast<whiteout::flakes::AssetsView::Stats*>(self)->liveSlots = value;
}

uint64_t whiteout_flakes_FlakesAssetsViewStats_get_loadedSlots(const whiteout_FlakesAssetsViewStats* self) {
    return reinterpret_cast<const whiteout::flakes::AssetsView::Stats*>(self)->loadedSlots;
}

void whiteout_flakes_FlakesAssetsViewStats_set_loadedSlots(whiteout_FlakesAssetsViewStats* self, uint64_t value) {
    reinterpret_cast<whiteout::flakes::AssetsView::Stats*>(self)->loadedSlots = value;
}

uint64_t whiteout_flakes_FlakesAssetsViewStats_get_pendingNeeds(const whiteout_FlakesAssetsViewStats* self) {
    return reinterpret_cast<const whiteout::flakes::AssetsView::Stats*>(self)->pendingNeeds;
}

void whiteout_flakes_FlakesAssetsViewStats_set_pendingNeeds(whiteout_FlakesAssetsViewStats* self, uint64_t value) {
    reinterpret_cast<whiteout::flakes::AssetsView::Stats*>(self)->pendingNeeds = value;
}

uint64_t whiteout_flakes_FlakesAssetsViewStats_get_totalAcquires(const whiteout_FlakesAssetsViewStats* self) {
    return reinterpret_cast<const whiteout::flakes::AssetsView::Stats*>(self)->totalAcquires;
}

void whiteout_flakes_FlakesAssetsViewStats_set_totalAcquires(whiteout_FlakesAssetsViewStats* self, uint64_t value) {
    reinterpret_cast<whiteout::flakes::AssetsView::Stats*>(self)->totalAcquires = value;
}

uint64_t whiteout_flakes_FlakesAssetsViewStats_get_totalReleases(const whiteout_FlakesAssetsViewStats* self) {
    return reinterpret_cast<const whiteout::flakes::AssetsView::Stats*>(self)->totalReleases;
}

void whiteout_flakes_FlakesAssetsViewStats_set_totalReleases(whiteout_FlakesAssetsViewStats* self, uint64_t value) {
    reinterpret_cast<whiteout::flakes::AssetsView::Stats*>(self)->totalReleases = value;
}

uint64_t whiteout_flakes_FlakesAssetsViewStats_get_totalApplies(const whiteout_FlakesAssetsViewStats* self) {
    return reinterpret_cast<const whiteout::flakes::AssetsView::Stats*>(self)->totalApplies;
}

void whiteout_flakes_FlakesAssetsViewStats_set_totalApplies(whiteout_FlakesAssetsViewStats* self, uint64_t value) {
    reinterpret_cast<whiteout::flakes::AssetsView::Stats*>(self)->totalApplies = value;
}

uint64_t whiteout_flakes_FlakesAssetsViewStats_get_totalApplyMisses(const whiteout_FlakesAssetsViewStats* self) {
    return reinterpret_cast<const whiteout::flakes::AssetsView::Stats*>(self)->totalApplyMisses;
}

void whiteout_flakes_FlakesAssetsViewStats_set_totalApplyMisses(whiteout_FlakesAssetsViewStats* self, uint64_t value) {
    reinterpret_cast<whiteout::flakes::AssetsView::Stats*>(self)->totalApplyMisses = value;
}

} // extern "C"

// ── FlakesDncView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesDncView_delete(whiteout_FlakesDncView* self) {
    delete reinterpret_cast<whiteout::flakes::DncView*>(self);
}

int32_t whiteout_flakes_FlakesDncView_IsValid(const whiteout_FlakesDncView* self) {
    return reinterpret_cast<const whiteout::flakes::DncView*>(self)->IsValid();
}

float whiteout_flakes_FlakesDncView_TimeOfDay(const whiteout_FlakesDncView* self) {
    return reinterpret_cast<const whiteout::flakes::DncView*>(self)->GetTimeOfDay();
}

void whiteout_flakes_FlakesDncView_SetTimeOfDay(whiteout_FlakesDncView* self, float arg) {
    reinterpret_cast<whiteout::flakes::DncView*>(self)->SetTimeOfDay(arg);
}

float whiteout_flakes_FlakesDncView_TodScale(const whiteout_FlakesDncView* self) {
    return reinterpret_cast<const whiteout::flakes::DncView*>(self)->GetTodScale();
}

void whiteout_flakes_FlakesDncView_SetTodScale(whiteout_FlakesDncView* self, float arg) {
    reinterpret_cast<whiteout::flakes::DncView*>(self)->SetTodScale(arg);
}

float whiteout_flakes_FlakesDncView_HoursPerDay(const whiteout_FlakesDncView* self) {
    return reinterpret_cast<const whiteout::flakes::DncView*>(self)->GetHoursPerDay();
}

void whiteout_flakes_FlakesDncView_SetUnitMdl(whiteout_FlakesDncView* self, const char* arg) {
    reinterpret_cast<whiteout::flakes::DncView*>(self)->SetUnitMdl(std::string(arg ? arg : ""));
}

void whiteout_flakes_FlakesDncView_Advance(whiteout_FlakesDncView* self, float dt) {
    reinterpret_cast<whiteout::flakes::DncView*>(self)->Advance(dt);
}

} // extern "C"

// ── FlakesShadowView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesShadowView_delete(whiteout_FlakesShadowView* self) {
    delete reinterpret_cast<whiteout::flakes::ShadowView*>(self);
}

int32_t whiteout_flakes_FlakesShadowView_IsValid(const whiteout_FlakesShadowView* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowView*>(self)->IsValid();
}

int32_t whiteout_flakes_FlakesShadowView_IsEnabled(const whiteout_FlakesShadowView* self) {
    return reinterpret_cast<const whiteout::flakes::ShadowView*>(self)->IsEnabled();
}

void whiteout_flakes_FlakesShadowView_SetEnabled(whiteout_FlakesShadowView* self, int32_t on) {
    reinterpret_cast<whiteout::flakes::ShadowView*>(self)->SetEnabled(on);
}

struct whiteout_FlakesShadowParams* whiteout_flakes_FlakesShadowView_Params(const whiteout_FlakesShadowView* self) {
    return reinterpret_cast<struct whiteout_FlakesShadowParams*>(
        new whiteout::flakes::ShadowParams(reinterpret_cast<const whiteout::flakes::ShadowView*>(self)->Params()));
}

void whiteout_flakes_FlakesShadowView_SetParams(whiteout_FlakesShadowView* self, struct whiteout_FlakesShadowParams* arg) {
    reinterpret_cast<whiteout::flakes::ShadowView*>(self)->SetParams(*reinterpret_cast<const whiteout::flakes::ShadowParams*>(arg));
}

} // extern "C"

// ── FlakesSplatView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesSplatView_delete(whiteout_FlakesSplatView* self) {
    delete reinterpret_cast<whiteout::flakes::SplatView*>(self);
}

void whiteout_flakes_FlakesSplatView_Clear(whiteout_FlakesSplatView* self) {
    reinterpret_cast<whiteout::flakes::SplatView*>(self)->Clear();
}

} // extern "C"

// ── FlakesReplaceablesView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesReplaceablesView_delete(whiteout_FlakesReplaceablesView* self) {
    delete reinterpret_cast<whiteout::flakes::ReplaceablesView*>(self);
}

int32_t whiteout_flakes_FlakesReplaceablesView_ConsumeDirty(whiteout_FlakesReplaceablesView* self) {
    return reinterpret_cast<whiteout::flakes::ReplaceablesView*>(self)->ConsumeDirty();
}

void whiteout_flakes_FlakesReplaceablesView_SetTileset(whiteout_FlakesReplaceablesView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::ReplaceablesView*>(self)->SetTileset(static_cast<whiteout::flakes::io::Tileset>(arg));
}

} // extern "C"

// ── FlakesPlaybackView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesPlaybackView_delete(whiteout_FlakesPlaybackView* self) {
    delete reinterpret_cast<whiteout::flakes::PlaybackView*>(self);
}

int32_t whiteout_flakes_FlakesPlaybackView_State(const whiteout_FlakesPlaybackView* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::PlaybackView*>(self)->GetState());
}

void whiteout_flakes_FlakesPlaybackView_SetState(whiteout_FlakesPlaybackView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::PlaybackView*>(self)->SetState(static_cast<whiteout::flakes::PlaybackState>(arg));
}

void whiteout_flakes_FlakesPlaybackView_Play(whiteout_FlakesPlaybackView* self) {
    reinterpret_cast<whiteout::flakes::PlaybackView*>(self)->Play();
}

void whiteout_flakes_FlakesPlaybackView_Pause(whiteout_FlakesPlaybackView* self) {
    reinterpret_cast<whiteout::flakes::PlaybackView*>(self)->Pause();
}

void whiteout_flakes_FlakesPlaybackView_Stop(whiteout_FlakesPlaybackView* self) {
    reinterpret_cast<whiteout::flakes::PlaybackView*>(self)->Stop();
}

void whiteout_flakes_FlakesPlaybackView_Restart(whiteout_FlakesPlaybackView* self) {
    reinterpret_cast<whiteout::flakes::PlaybackView*>(self)->Restart();
}

void whiteout_flakes_FlakesPlaybackView_ResyncEffects(whiteout_FlakesPlaybackView* self) {
    reinterpret_cast<whiteout::flakes::PlaybackView*>(self)->ResyncEffects();
}

int32_t whiteout_flakes_FlakesPlaybackView_IsPaused(const whiteout_FlakesPlaybackView* self) {
    return reinterpret_cast<const whiteout::flakes::PlaybackView*>(self)->IsPaused();
}

float whiteout_flakes_FlakesPlaybackView_TimeScale(const whiteout_FlakesPlaybackView* self) {
    return reinterpret_cast<const whiteout::flakes::PlaybackView*>(self)->GetTimeScale();
}

void whiteout_flakes_FlakesPlaybackView_SetTimeScale(whiteout_FlakesPlaybackView* self, float arg) {
    reinterpret_cast<whiteout::flakes::PlaybackView*>(self)->SetTimeScale(arg);
}

} // extern "C"

// ── FlakesActorView ─────────────────────────────────────────────────

extern "C" {

void whiteout_flakes_FlakesActorView_delete(whiteout_FlakesActorView* self) {
    delete reinterpret_cast<whiteout::flakes::ActorView*>(self);
}

int32_t whiteout_flakes_FlakesActorView_IsValid(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->IsValid();
}

uint32_t whiteout_flakes_FlakesActorView_Handle(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->Handle();
}

int32_t whiteout_flakes_FlakesActorView_Role(const whiteout_FlakesActorView* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::ActorView*>(self)->Role());
}

float whiteout_flakes_FlakesActorView_PlaybackSpeed(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->PlaybackSpeed();
}

void whiteout_flakes_FlakesActorView_SetPlaybackSpeed(whiteout_FlakesActorView* self, float arg) {
    reinterpret_cast<whiteout::flakes::ActorView*>(self)->SetPlaybackSpeed(arg);
}

int32_t whiteout_flakes_FlakesActorView_IgnoreNonLooping(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->IgnoreNonLooping();
}

void whiteout_flakes_FlakesActorView_SetIgnoreNonLooping(whiteout_FlakesActorView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::ActorView*>(self)->SetIgnoreNonLooping(arg);
}

uint32_t whiteout_flakes_FlakesActorView_TeamColor(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->TeamColor();
}

void whiteout_flakes_FlakesActorView_SetTeamColor(whiteout_FlakesActorView* self, uint8_t r, uint8_t g, uint8_t b) {
    reinterpret_cast<whiteout::flakes::ActorView*>(self)->SetTeamColor(r, g, b);
}

void whiteout_flakes_FlakesActorView_SetRoleExternal(whiteout_FlakesActorView* self) {
    reinterpret_cast<whiteout::flakes::ActorView*>(self)->SetRoleExternal();
}

struct whiteout_SequenceInfoList* whiteout_flakes_FlakesActorView_Sequences(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<struct whiteout_SequenceInfoList*>(
        new std::vector<whiteout::flakes::SequenceInfo>(reinterpret_cast<const whiteout::flakes::ActorView*>(self)->Sequences()));
}

int32_t whiteout_flakes_FlakesActorView_ActiveSequenceIndex(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->ActiveSequenceIndex();
}

void whiteout_flakes_FlakesActorView_SetActiveSequence(whiteout_FlakesActorView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::ActorView*>(self)->SetActiveSequence(arg);
}

int32_t whiteout_flakes_FlakesActorView_AnimationTimeMs(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->AnimationTimeMs();
}

void whiteout_flakes_FlakesActorView_SetAnimationTimeMs(whiteout_FlakesActorView* self, int32_t arg) {
    reinterpret_cast<whiteout::flakes::ActorView*>(self)->SetAnimationTimeMs(arg);
}

int32_t whiteout_flakes_FlakesActorView_HasAnimationSource(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->HasAnimationSource();
}

void whiteout_flakes_FlakesActorView_EvaluateAndApply(whiteout_FlakesActorView* self) {
    reinterpret_cast<whiteout::flakes::ActorView*>(self)->EvaluateAndApply();
}

void whiteout_flakes_FlakesActorView_EvaluateAt(whiteout_FlakesActorView* self, int32_t timeMs) {
    reinterpret_cast<whiteout::flakes::ActorView*>(self)->EvaluateAt(timeMs);
}

int32_t whiteout_flakes_FlakesActorView_GeosetCount(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->GeosetCount();
}

int32_t whiteout_flakes_FlakesActorView_MaterialCount(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->MaterialCount();
}

int32_t whiteout_flakes_FlakesActorView_CollisionShapeCount(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->CollisionShapeCount();
}

struct whiteout_CameraPresetList* whiteout_flakes_FlakesActorView_CameraPresets(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<struct whiteout_CameraPresetList*>(
        new std::vector<whiteout::flakes::CameraPreset>(reinterpret_cast<const whiteout::flakes::ActorView*>(self)->CameraPresets()));
}

int32_t whiteout_flakes_FlakesActorView_PreferredRenderMode(const whiteout_FlakesActorView* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::ActorView*>(self)->PreferredRenderMode());
}

size_t whiteout_flakes_FlakesActorView_ChildModelPaths_count(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<const whiteout::flakes::ActorView*>(self)->ChildModelPaths().size();
}

whiteout_CString whiteout_flakes_FlakesActorView_ChildModelPaths_at(const whiteout_FlakesActorView* self, size_t index) {
    const auto& __v = reinterpret_cast<const whiteout::flakes::ActorView*>(self)->ChildModelPaths();
    if (index >= __v.size()) return emptyCString();
    return wrapCString(std::string(__v[index]));
}


struct whiteout_StringList* whiteout_flakes_FlakesActorView_ChildModelPaths(const whiteout_FlakesActorView* self) {
    return reinterpret_cast<struct whiteout_StringList*>(
        new std::vector<std::string>(
            reinterpret_cast<const whiteout::flakes::ActorView*>(self)->ChildModelPaths()));
}
} // extern "C"

// ── FlakesRenderer ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesRenderer* whiteout_flakes_FlakesRenderer_new(void) {
    return reinterpret_cast<whiteout_FlakesRenderer*>(new whiteout::flakes::Renderer());
}

void whiteout_flakes_FlakesRenderer_delete(whiteout_FlakesRenderer* self) {
    delete reinterpret_cast<whiteout::flakes::Renderer*>(self);
}

struct whiteout_FlakesPipelineView* whiteout_flakes_FlakesRenderer_Pipeline(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesPipelineView*>(
        new whiteout::flakes::PipelineView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Pipeline()));
}

struct whiteout_FlakesSceneView* whiteout_flakes_FlakesRenderer_Scene(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesSceneView*>(
        new whiteout::flakes::SceneView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Scene()));
}

struct whiteout_FlakesCameraView* whiteout_flakes_FlakesRenderer_Camera(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesCameraView*>(
        new whiteout::flakes::CameraView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Camera()));
}

uint32_t whiteout_flakes_FlakesRenderer_CreateCamera(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<whiteout::flakes::Renderer*>(self)->CreateCamera();
}

struct whiteout_FlakesCameraView* whiteout_flakes_FlakesRenderer_CameraAt(whiteout_FlakesRenderer* self, uint32_t arg) {
    return reinterpret_cast<struct whiteout_FlakesCameraView*>(
        new whiteout::flakes::CameraView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->CameraAt(arg)));
}

struct whiteout_FlakesSettingsView* whiteout_flakes_FlakesRenderer_Settings(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesSettingsView*>(
        new whiteout::flakes::SettingsView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Settings()));
}

struct whiteout_FlakesLoaderView* whiteout_flakes_FlakesRenderer_Loader(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesLoaderView*>(
        new whiteout::flakes::LoaderView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Loader()));
}

struct whiteout_FlakesDncView* whiteout_flakes_FlakesRenderer_Dnc(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesDncView*>(
        new whiteout::flakes::DncView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Dnc()));
}

struct whiteout_FlakesShadowView* whiteout_flakes_FlakesRenderer_Shadow(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesShadowView*>(
        new whiteout::flakes::ShadowView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Shadow()));
}

struct whiteout_FlakesSplatView* whiteout_flakes_FlakesRenderer_Splats(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesSplatView*>(
        new whiteout::flakes::SplatView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Splats()));
}

struct whiteout_FlakesReplaceablesView* whiteout_flakes_FlakesRenderer_Replaceables(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesReplaceablesView*>(
        new whiteout::flakes::ReplaceablesView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Replaceables()));
}

struct whiteout_FlakesAssetsView* whiteout_flakes_FlakesRenderer_Assets(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesAssetsView*>(
        new whiteout::flakes::AssetsView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Assets()));
}

struct whiteout_FlakesPlaybackView* whiteout_flakes_FlakesRenderer_Playback(whiteout_FlakesRenderer* self) {
    return reinterpret_cast<struct whiteout_FlakesPlaybackView*>(
        new whiteout::flakes::PlaybackView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Playback()));
}

struct whiteout_FlakesActorView* whiteout_flakes_FlakesRenderer_Actor(whiteout_FlakesRenderer* self, uint32_t h) {
    return reinterpret_cast<struct whiteout_FlakesActorView*>(
        new whiteout::flakes::ActorView(reinterpret_cast<whiteout::flakes::Renderer*>(self)->Actor(h)));
}

void whiteout_flakes_FlakesRenderer_Tick(whiteout_FlakesRenderer* self, float dt) {
    reinterpret_cast<whiteout::flakes::Renderer*>(self)->Tick(dt);
}

} // extern "C"

// ── FlakesStorageBrowser ─────────────────────────────────────────────────

extern "C" {

whiteout_FlakesStorageBrowser* whiteout_flakes_FlakesStorageBrowser_new(void) {
    return reinterpret_cast<whiteout_FlakesStorageBrowser*>(new whiteout::flakes::StorageBrowser());
}

void whiteout_flakes_FlakesStorageBrowser_delete(whiteout_FlakesStorageBrowser* self) {
    delete reinterpret_cast<whiteout::flakes::StorageBrowser*>(self);
}

int32_t whiteout_flakes_FlakesStorageBrowser_Open(whiteout_FlakesStorageBrowser* self, const char* root, int32_t kind) {
    return reinterpret_cast<whiteout::flakes::StorageBrowser*>(self)->Open(std::string(root ? root : ""), static_cast<whiteout::flakes::StorageKind>(kind));
}

int32_t whiteout_flakes_FlakesStorageBrowser_OpenAuto(whiteout_FlakesStorageBrowser* self, const char* path) {
    return reinterpret_cast<whiteout::flakes::StorageBrowser*>(self)->OpenAuto(std::string(path ? path : ""));
}

int32_t whiteout_flakes_FlakesStorageBrowser_Kind(const whiteout_FlakesStorageBrowser* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->GetKind());
}

int32_t whiteout_flakes_FlakesStorageBrowser_IsOpen(const whiteout_FlakesStorageBrowser* self) {
    return reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->IsOpen();
}

whiteout_CString whiteout_flakes_FlakesStorageBrowser_Root(const whiteout_FlakesStorageBrowser* self) {
    return wrapCString(reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->GetRoot());
}

whiteout_CString whiteout_flakes_FlakesStorageBrowser_LastError(const whiteout_FlakesStorageBrowser* self) {
    return wrapCString(reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->GetLastError());
}

whiteout_CString whiteout_flakes_FlakesStorageBrowser_CurrentPath(const whiteout_FlakesStorageBrowser* self) {
    return wrapCString(reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->GetCurrentPath());
}

size_t whiteout_flakes_FlakesStorageBrowser_Breadcrumb_count(const whiteout_FlakesStorageBrowser* self) {
    return reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Breadcrumb().size();
}

whiteout_CString whiteout_flakes_FlakesStorageBrowser_Breadcrumb_at(const whiteout_FlakesStorageBrowser* self, size_t index) {
    const auto& __v = reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Breadcrumb();
    if (index >= __v.size()) return emptyCString();
    return wrapCString(std::string(__v[index]));
}


struct whiteout_StringList* whiteout_flakes_FlakesStorageBrowser_Breadcrumb(const whiteout_FlakesStorageBrowser* self) {
    return reinterpret_cast<struct whiteout_StringList*>(
        new std::vector<std::string>(
            reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Breadcrumb()));
}
size_t whiteout_flakes_FlakesStorageBrowser_Folders_count(const whiteout_FlakesStorageBrowser* self) {
    return reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Folders().size();
}

whiteout_CString whiteout_flakes_FlakesStorageBrowser_Folders_at(const whiteout_FlakesStorageBrowser* self, size_t index) {
    const auto& __v = reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Folders();
    if (index >= __v.size()) return emptyCString();
    return wrapCString(std::string(__v[index]));
}


struct whiteout_StringList* whiteout_flakes_FlakesStorageBrowser_Folders(const whiteout_FlakesStorageBrowser* self) {
    return reinterpret_cast<struct whiteout_StringList*>(
        new std::vector<std::string>(
            reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Folders()));
}
size_t whiteout_flakes_FlakesStorageBrowser_Files_count(const whiteout_FlakesStorageBrowser* self) {
    return reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Files().size();
}

whiteout_CString whiteout_flakes_FlakesStorageBrowser_Files_at(const whiteout_FlakesStorageBrowser* self, size_t index) {
    const auto& __v = reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Files();
    if (index >= __v.size()) return emptyCString();
    return wrapCString(std::string(__v[index]));
}


struct whiteout_StringList* whiteout_flakes_FlakesStorageBrowser_Files(const whiteout_FlakesStorageBrowser* self) {
    return reinterpret_cast<struct whiteout_StringList*>(
        new std::vector<std::string>(
            reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->Files()));
}
void whiteout_flakes_FlakesStorageBrowser_SetFilter(whiteout_FlakesStorageBrowser* self, int32_t filter) {
    reinterpret_cast<whiteout::flakes::StorageBrowser*>(self)->SetFilter(static_cast<whiteout::flakes::StorageFileFilter>(filter));
}

int32_t whiteout_flakes_FlakesStorageBrowser_Filter(const whiteout_FlakesStorageBrowser* self) {
    return static_cast<int32_t>(reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->GetFilter());
}

int32_t whiteout_flakes_FlakesStorageBrowser_UnfilteredFileCount(const whiteout_FlakesStorageBrowser* self) {
    return reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->UnfilteredFileCount();
}

void whiteout_flakes_FlakesStorageBrowser_Descend(whiteout_FlakesStorageBrowser* self, const char* folderName) {
    reinterpret_cast<whiteout::flakes::StorageBrowser*>(self)->Descend(std::string(folderName ? folderName : ""));
}

void whiteout_flakes_FlakesStorageBrowser_Ascend(whiteout_FlakesStorageBrowser* self) {
    reinterpret_cast<whiteout::flakes::StorageBrowser*>(self)->Ascend();
}

void whiteout_flakes_FlakesStorageBrowser_NavigateTo(whiteout_FlakesStorageBrowser* self, const char* displayPath) {
    reinterpret_cast<whiteout::flakes::StorageBrowser*>(self)->NavigateTo(std::string(displayPath ? displayPath : ""));
}

whiteout_CString whiteout_flakes_FlakesStorageBrowser_ChildPath(const whiteout_FlakesStorageBrowser* self, const char* fileName) {
    return wrapCString(reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->ChildPath(std::string(fileName ? fileName : "")));
}

int32_t whiteout_flakes_FlakesStorageBrowser_IsEffect(const whiteout_FlakesStorageBrowser* self, const char* fileName) {
    return reinterpret_cast<const whiteout::flakes::StorageBrowser*>(self)->IsEffect(std::string(fileName ? fileName : ""));
}

} // extern "C"

