/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2026 Fernando Sahmkow */
/* AUTOGENERATED by tools/codegen/emit_c.py — do not edit. */
/* Regenerate via:  python -m tools.codegen.codegen flakes --backend c-header */

#ifndef WHITEOUT_FLAKES_H
#define WHITEOUT_FLAKES_H

#include "whiteout_c_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ── Owned string list ───────── */

typedef struct whiteout_StringList whiteout_StringList;
size_t whiteout_flakes_StringList_size(const whiteout_StringList* self);
/* Borrowed; valid until the list is destroyed. */
whiteout_CString whiteout_flakes_StringList_at(whiteout_StringList* self, size_t index);
void whiteout_flakes_StringList_delete(whiteout_StringList* self);

/* ── Owned handle lists ───────── */

typedef struct whiteout_SequenceInfoList whiteout_SequenceInfoList;
size_t whiteout_flakes_SequenceInfoList_size(const whiteout_SequenceInfoList* self);
/* Borrowed element; valid until the list is destroyed. */
struct whiteout_SequenceInfo* whiteout_flakes_SequenceInfoList_at(whiteout_SequenceInfoList* self, size_t index);
void whiteout_flakes_SequenceInfoList_delete(whiteout_SequenceInfoList* self);
typedef struct whiteout_CameraPresetList whiteout_CameraPresetList;
size_t whiteout_flakes_CameraPresetList_size(const whiteout_CameraPresetList* self);
/* Borrowed element; valid until the list is destroyed. */
struct whiteout_CameraPreset* whiteout_flakes_CameraPresetList_at(whiteout_CameraPresetList* self, size_t index);
void whiteout_flakes_CameraPresetList_delete(whiteout_CameraPresetList* self);

/* ── Enums ─────────────────────────────────────────────────── */

typedef enum {
    whiteout_flakes_GfxApi_D3D11,
    whiteout_flakes_GfxApi_D3D12,
    whiteout_flakes_GfxApi_Vulkan,
    whiteout_flakes_GfxApi_WebGPU,
    whiteout_flakes_GfxApi_Metal,
} whiteout_flakes_GfxApi;

typedef enum {
    whiteout_flakes_RenderMode_SD,
    whiteout_flakes_RenderMode_HD,
} whiteout_flakes_RenderMode;

typedef enum {
    whiteout_flakes_PlaybackState_Playing,
    whiteout_flakes_PlaybackState_Paused,
    whiteout_flakes_PlaybackState_Stopped,
} whiteout_flakes_PlaybackState;

typedef enum {
    whiteout_flakes_LightingMode_InGame,
    whiteout_flakes_LightingMode_Glue,
    whiteout_flakes_LightingMode_Dynamic,
} whiteout_flakes_LightingMode;

typedef enum {
    whiteout_flakes_IblMode_Portrait,
    whiteout_flakes_IblMode_DayNight,
    whiteout_flakes_IblMode_Dungeon,
    whiteout_flakes_IblMode_Sunset,
} whiteout_flakes_IblMode;

typedef enum {
    whiteout_flakes_ActorRole_Unit,
    whiteout_flakes_ActorRole_External,
    whiteout_flakes_ActorRole_Attachment,
    whiteout_flakes_ActorRole_PE1,
    whiteout_flakes_ActorRole_SPN,
} whiteout_flakes_ActorRole;

typedef enum {
    whiteout_flakes_Tileset_LordaeronSummer,
    whiteout_flakes_Tileset_Ashenvale,
    whiteout_flakes_Tileset_Barrens,
    whiteout_flakes_Tileset_Northrend,
    whiteout_flakes_Tileset_Felwood,
    whiteout_flakes_Tileset_Dungeon,
    whiteout_flakes_Tileset_Cityscape,
    whiteout_flakes_Tileset_LordaeronFall,
    whiteout_flakes_Tileset_LordaeronWinter,
    whiteout_flakes_Tileset_Outland,
    whiteout_flakes_Tileset_SunkenRuins,
    whiteout_flakes_Tileset_IcecrownGlacier,
    whiteout_flakes_Tileset_DalaranRuins,
    whiteout_flakes_Tileset_BlackCitadel,
    whiteout_flakes_Tileset_Underground,
    whiteout_flakes_Tileset_Village,
    whiteout_flakes_Tileset_Count,
} whiteout_flakes_Tileset;

typedef enum {
    whiteout_flakes_Mode_Orbital,
    whiteout_flakes_Mode_Direct,
} whiteout_flakes_Mode;

typedef enum {
    whiteout_flakes_Kind_Texture,
    whiteout_flakes_Kind_Particle,
    whiteout_flakes_Kind_ChildModel,
} whiteout_flakes_Kind;

typedef enum {
    whiteout_flakes_StorageKind_Casc,
    whiteout_flakes_StorageKind_Mpq,
    whiteout_flakes_StorageKind_Folder,
} whiteout_flakes_StorageKind;

typedef enum {
    whiteout_flakes_StorageFileFilter_All,
    whiteout_flakes_StorageFileFilter_ModelsOnly,
    whiteout_flakes_StorageFileFilter_EffectsOnly,
} whiteout_flakes_StorageFileFilter;

/* ── Opaque handles ───────────────────────────────────────── */

typedef struct whiteout_FlakesRect whiteout_FlakesRect;
typedef struct whiteout_FlakesShadowParams whiteout_FlakesShadowParams;
typedef struct whiteout_FlakesDisplayFlags whiteout_FlakesDisplayFlags;
typedef struct whiteout_FlakesFrameStats whiteout_FlakesFrameStats;
typedef struct whiteout_FlakesCameraPreset whiteout_FlakesCameraPreset;
typedef struct whiteout_FlakesSequenceInfo whiteout_FlakesSequenceInfo;
typedef struct whiteout_FlakesPipelineView whiteout_FlakesPipelineView;
typedef struct whiteout_FlakesSceneView whiteout_FlakesSceneView;
typedef struct whiteout_FlakesCameraView whiteout_FlakesCameraView;
typedef struct whiteout_FlakesSettingsView whiteout_FlakesSettingsView;
typedef struct whiteout_FlakesLoaderView whiteout_FlakesLoaderView;
typedef struct whiteout_FlakesAssetsView whiteout_FlakesAssetsView;
typedef struct whiteout_FlakesAssetsViewStats whiteout_FlakesAssetsViewStats;
typedef struct whiteout_FlakesDncView whiteout_FlakesDncView;
typedef struct whiteout_FlakesShadowView whiteout_FlakesShadowView;
typedef struct whiteout_FlakesSplatView whiteout_FlakesSplatView;
typedef struct whiteout_FlakesReplaceablesView whiteout_FlakesReplaceablesView;
typedef struct whiteout_FlakesPlaybackView whiteout_FlakesPlaybackView;
typedef struct whiteout_FlakesActorView whiteout_FlakesActorView;
typedef struct whiteout_FlakesRenderer whiteout_FlakesRenderer;
typedef struct whiteout_FlakesStorageBrowser whiteout_FlakesStorageBrowser;

/* ── FlakesRect ─────────────────────────────────────────────── */

/* Integer-coordinate screen-space rectangle (top-down, pixel units). */
/*  */
/* Used by host frontends for laying out UI overlays. */
whiteout_FlakesRect* whiteout_flakes_FlakesRect_new(void);
void whiteout_flakes_FlakesRect_delete(whiteout_FlakesRect* self);

int32_t whiteout_flakes_FlakesRect_get_left(const whiteout_FlakesRect* self);
void whiteout_flakes_FlakesRect_set_left(whiteout_FlakesRect* self, int32_t value);
int32_t whiteout_flakes_FlakesRect_get_top(const whiteout_FlakesRect* self);
void whiteout_flakes_FlakesRect_set_top(whiteout_FlakesRect* self, int32_t value);
int32_t whiteout_flakes_FlakesRect_get_right(const whiteout_FlakesRect* self);
void whiteout_flakes_FlakesRect_set_right(whiteout_FlakesRect* self, int32_t value);
int32_t whiteout_flakes_FlakesRect_get_bottom(const whiteout_FlakesRect* self);
void whiteout_flakes_FlakesRect_set_bottom(whiteout_FlakesRect* self, int32_t value);

/* ── FlakesShadowParams ─────────────────────────────────────────────── */

/* Cascade-shadow-map tuning consumed by `ShadowService`. */
/*  */
/* `enabled = false` disables shadows entirely (no shadow pass, no sampler binds). When enabled, `cascadeCount` cascades of `cascadeResolution × cascadeResolution` each are rendered every frame; `lambdaSplit` mixes uniform and logarithmic cascade distribution (0 = uniform, 1 = log). */
whiteout_FlakesShadowParams* whiteout_flakes_FlakesShadowParams_new(void);
void whiteout_flakes_FlakesShadowParams_delete(whiteout_FlakesShadowParams* self);

/* Number of cascades; the renderer accepts 1..3. */
int32_t whiteout_flakes_FlakesShadowParams_get_cascadeCount(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_cascadeCount(whiteout_FlakesShadowParams* self, int32_t value);
/* Per-cascade shadow-map side length in texels. */
int32_t whiteout_flakes_FlakesShadowParams_get_cascadeResolution(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_cascadeResolution(whiteout_FlakesShadowParams* self, int32_t value);
/* Extruded receiver-height padding for the cascade frustums; larger values include taller casters in the cascade at a quality cost. */
float whiteout_flakes_FlakesShadowParams_get_casterHeight(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_casterHeight(whiteout_FlakesShadowParams* self, float value);
/* Cascade-distribution lambda: 0 = uniform splits, 1 = logarithmic. */
float whiteout_flakes_FlakesShadowParams_get_lambdaSplit(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_lambdaSplit(whiteout_FlakesShadowParams* self, float value);
/* @name Depth-bias tuning (passed to the rasterizer state). Defaults sized for a D32_FLOAT cascade with the LessEqual PCF compare op. Zero biases let rasterizer floating-point noise swing the depth comparison both ways on near-coplanar fragments; the 3×3 PCF averages that salt-and-pepper into ~50% lit and the scene looks uniformly darker than it should. A small constant offset + slope-scaled term keeps lit fragments lit while still catching actual occluders. @{ */
int32_t whiteout_flakes_FlakesShadowParams_get_depthBias(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_depthBias(whiteout_FlakesShadowParams* self, int32_t value);
float whiteout_flakes_FlakesShadowParams_get_slopeScaledBias(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_slopeScaledBias(whiteout_FlakesShadowParams* self, float value);
float whiteout_flakes_FlakesShadowParams_get_depthBiasClamp(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_depthBiasClamp(whiteout_FlakesShadowParams* self, float value);
/* Snap cascade origin to texel grid to suppress shimmering as the camera moves. */
int32_t whiteout_flakes_FlakesShadowParams_get_texelSnap(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_texelSnap(whiteout_FlakesShadowParams* self, int32_t value);
/* Master enable. Off ⇒ no shadow pass; the lit pass binds a 1×1 white sampler so PCF reads return "lit". */
int32_t whiteout_flakes_FlakesShadowParams_get_enabled(const whiteout_FlakesShadowParams* self);
void whiteout_flakes_FlakesShadowParams_set_enabled(whiteout_FlakesShadowParams* self, int32_t value);

/* ── FlakesDisplayFlags ─────────────────────────────────────────────── */

/* Toggles for what the renderer draws each frame. */
/*  */
/* Persisted by the host as a single block; defaults shown match the out-of-the-box viewer experience. */
whiteout_FlakesDisplayFlags* whiteout_flakes_FlakesDisplayFlags_new(void);
void whiteout_flakes_FlakesDisplayFlags_delete(whiteout_FlakesDisplayFlags* self);

/* Reference grid on the ground plane. */
int32_t whiteout_flakes_FlakesDisplayFlags_get_showGrid(const whiteout_FlakesDisplayFlags* self);
void whiteout_flakes_FlakesDisplayFlags_set_showGrid(whiteout_FlakesDisplayFlags* self, int32_t value);
/* MDX particle emitters. */
int32_t whiteout_flakes_FlakesDisplayFlags_get_showParticles(const whiteout_FlakesDisplayFlags* self);
void whiteout_flakes_FlakesDisplayFlags_set_showParticles(whiteout_FlakesDisplayFlags* self, int32_t value);
/* MDX ribbon emitters. */
int32_t whiteout_flakes_FlakesDisplayFlags_get_showRibbons(const whiteout_FlakesDisplayFlags* self);
void whiteout_flakes_FlakesDisplayFlags_set_showRibbons(whiteout_FlakesDisplayFlags* self, int32_t value);
/* Debug overlay for collision shapes. */
int32_t whiteout_flakes_FlakesDisplayFlags_get_showCollisions(const whiteout_FlakesDisplayFlags* self);
void whiteout_flakes_FlakesDisplayFlags_set_showCollisions(whiteout_FlakesDisplayFlags* self, int32_t value);
/* Debug overlay for light positions. */
int32_t whiteout_flakes_FlakesDisplayFlags_get_showLights(const whiteout_FlakesDisplayFlags* self);
void whiteout_flakes_FlakesDisplayFlags_set_showLights(whiteout_FlakesDisplayFlags* self, int32_t value);
/* MDX event objects (SPN / SPL / SND). */
int32_t whiteout_flakes_FlakesDisplayFlags_get_showEvents(const whiteout_FlakesDisplayFlags* self);
void whiteout_flakes_FlakesDisplayFlags_set_showEvents(whiteout_FlakesDisplayFlags* self, int32_t value);
/* Material path (SD vs HD). */
int32_t whiteout_flakes_FlakesDisplayFlags_get_renderMode(const whiteout_FlakesDisplayFlags* self);
void whiteout_flakes_FlakesDisplayFlags_set_renderMode(whiteout_FlakesDisplayFlags* self, int32_t value);

/* ── FlakesFrameStats ─────────────────────────────────────────────── */

/* Per-frame statistics aggregated by the pipeline. */
/*  */
/* Names mirror the internal `RenderPipeline::GetFrameStats` out parameters. Hosts surface these in title-bar / overlay HUDs. */
whiteout_FlakesFrameStats* whiteout_flakes_FlakesFrameStats_new(void);
void whiteout_flakes_FlakesFrameStats_delete(whiteout_FlakesFrameStats* self);

int32_t whiteout_flakes_FlakesFrameStats_get_geosets(const whiteout_FlakesFrameStats* self);
void whiteout_flakes_FlakesFrameStats_set_geosets(whiteout_FlakesFrameStats* self, int32_t value);
int32_t whiteout_flakes_FlakesFrameStats_get_textures(const whiteout_FlakesFrameStats* self);
void whiteout_flakes_FlakesFrameStats_set_textures(whiteout_FlakesFrameStats* self, int32_t value);
int32_t whiteout_flakes_FlakesFrameStats_get_nodes(const whiteout_FlakesFrameStats* self);
void whiteout_flakes_FlakesFrameStats_set_nodes(whiteout_FlakesFrameStats* self, int32_t value);
/* Live legacy (PE2) particles. Does **not** include corn effects — that is a separate simulation, counted by @ref cornParticles. */
int32_t whiteout_flakes_FlakesFrameStats_get_particles(const whiteout_FlakesFrameStats* self);
void whiteout_flakes_FlakesFrameStats_set_particles(whiteout_FlakesFrameStats* self, int32_t value);
int32_t whiteout_flakes_FlakesFrameStats_get_segments(const whiteout_FlakesFrameStats* self);
void whiteout_flakes_FlakesFrameStats_set_segments(whiteout_FlakesFrameStats* self, int32_t value);
/* Live corn-effects particles across every registered emitter. Separate from @ref particles because the two are different simulations with different lifetimes, and a host watching one learns nothing about the other. */
int32_t whiteout_flakes_FlakesFrameStats_get_cornParticles(const whiteout_FlakesFrameStats* self);
void whiteout_flakes_FlakesFrameStats_set_cornParticles(whiteout_FlakesFrameStats* self, int32_t value);

/* ── FlakesCameraPreset ─────────────────────────────────────────────── */

/* Scripted camera the host may select for a loaded model. */
/*  */
/* Mirrors the engine's MDX camera-chunk semantics: a static pose (`position` / `target` / FoV / clip planes / roll) plus an optional per-frame animator that overrides them based on the active sequence's time cursor. */
whiteout_FlakesCameraPreset* whiteout_flakes_FlakesCameraPreset_new(void);
void whiteout_flakes_FlakesCameraPreset_delete(whiteout_FlakesCameraPreset* self);

/* UTF-8 preset name as authored by the artist (used by host UI dropdowns); was `std::wstring` historically but normalised to UTF-8 so the same string flows from the MDX adapter through the UI without per-platform wide-char roundtrips. */
whiteout_CString whiteout_flakes_FlakesCameraPreset_get_name(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_name(whiteout_FlakesCameraPreset* self, const char* value);
/* `true` if this preset should drive the camera every frame (i.e. the user can't free-orbit while it's active). */
int32_t whiteout_flakes_FlakesCameraPreset_get_isLive(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_isLive(whiteout_FlakesCameraPreset* self, int32_t value);
/* Diagonal field of view (radians). */
float whiteout_flakes_FlakesCameraPreset_get_fovDiagonal(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_fovDiagonal(whiteout_FlakesCameraPreset* self, float value);
/* Near clip plane. */
float whiteout_flakes_FlakesCameraPreset_get_zNear(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_zNear(whiteout_FlakesCameraPreset* self, float value);
/* Far clip plane. */
float whiteout_flakes_FlakesCameraPreset_get_zFar(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_zFar(whiteout_FlakesCameraPreset* self, float value);
/* Roll around the view axis (radians). */
float whiteout_flakes_FlakesCameraPreset_get_staticRoll(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_staticRoll(whiteout_FlakesCameraPreset* self, float value);
/* @name Derived orbital pose @{ Convenience values populated by the MDX adapter for free-camera fallback (`pitch`/`yaw` in radians, `distance` from `target`). */
float whiteout_flakes_FlakesCameraPreset_get_pitch(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_pitch(whiteout_FlakesCameraPreset* self, float value);
float whiteout_flakes_FlakesCameraPreset_get_yaw(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_yaw(whiteout_FlakesCameraPreset* self, float value);
float whiteout_flakes_FlakesCameraPreset_get_distance(const whiteout_FlakesCameraPreset* self);
void whiteout_flakes_FlakesCameraPreset_set_distance(whiteout_FlakesCameraPreset* self, float value);

/* ── FlakesSequenceInfo ─────────────────────────────────────────────── */

/* Description of one animation sequence (`SEQS` chunk entry). */
/*  */
/* Times are in milliseconds (matches MDX's internal unit). `moveSpeed` is the artist-authored locomotion speed in world-units / second, used by hosts to drive walk-cycle drift along the camera axis. */
whiteout_FlakesSequenceInfo* whiteout_flakes_FlakesSequenceInfo_new(void);
void whiteout_flakes_FlakesSequenceInfo_delete(whiteout_FlakesSequenceInfo* self);

whiteout_CString whiteout_flakes_FlakesSequenceInfo_get_name(const whiteout_FlakesSequenceInfo* self);
void whiteout_flakes_FlakesSequenceInfo_set_name(whiteout_FlakesSequenceInfo* self, const char* value);
int32_t whiteout_flakes_FlakesSequenceInfo_get_startMs(const whiteout_FlakesSequenceInfo* self);
void whiteout_flakes_FlakesSequenceInfo_set_startMs(whiteout_FlakesSequenceInfo* self, int32_t value);
int32_t whiteout_flakes_FlakesSequenceInfo_get_endMs(const whiteout_FlakesSequenceInfo* self);
void whiteout_flakes_FlakesSequenceInfo_set_endMs(whiteout_FlakesSequenceInfo* self, int32_t value);
float whiteout_flakes_FlakesSequenceInfo_get_moveSpeed(const whiteout_FlakesSequenceInfo* self);
void whiteout_flakes_FlakesSequenceInfo_set_moveSpeed(whiteout_FlakesSequenceInfo* self, float value);
float whiteout_flakes_FlakesSequenceInfo_get_rarity(const whiteout_FlakesSequenceInfo* self);
void whiteout_flakes_FlakesSequenceInfo_set_rarity(whiteout_FlakesSequenceInfo* self, float value);
int32_t whiteout_flakes_FlakesSequenceInfo_get_nonLooping(const whiteout_FlakesSequenceInfo* self);
void whiteout_flakes_FlakesSequenceInfo_set_nonLooping(whiteout_FlakesSequenceInfo* self, int32_t value);

/* ── FlakesPipelineView ─────────────────────────────────────────────── */

/* Swap-chain + frame-submit surface. */
void whiteout_flakes_FlakesPipelineView_delete(whiteout_FlakesPipelineView* self);

/* Create the gfx device. Must succeed before any other pipeline call. Picks the platform-default backend if @p api is `Vulkan` on non-Windows. */
void whiteout_flakes_FlakesPipelineView_InitDevice(whiteout_FlakesPipelineView* self, int32_t arg);
int32_t whiteout_flakes_FlakesPipelineView_IsDeviceReady(const whiteout_FlakesPipelineView* self);
/* Create a headless (off-screen) target with no swap-chain. RenderFrame / RenderViewport draw into it; Present no-ops on it. Read the result back via the frame-capture ring. Use for thumbnail / render-to-texture viewports that aren't shown in a window. */
uint32_t whiteout_flakes_FlakesPipelineView_CreateOffscreenTarget(whiteout_FlakesPipelineView* self, int32_t width, int32_t height);
/* Destroy a target (swap-chain or off-screen) and free its GPU memory. Safe to call on any target id; clears primary if it was. */
void whiteout_flakes_FlakesPipelineView_DestroyTarget(whiteout_FlakesPipelineView* self, uint32_t arg);
/* Mark a target as the main one (frame stats track this one). */
void whiteout_flakes_FlakesPipelineView_SetPrimaryTarget(whiteout_FlakesPipelineView* self, uint32_t arg);
/* Resize the primary target's swap-chain. */
void whiteout_flakes_FlakesPipelineView_ResizePrimaryTarget(whiteout_FlakesPipelineView* self, int32_t width, int32_t height);
/* Render the scene's default camera to @p t. */
void whiteout_flakes_FlakesPipelineView_RenderFrame(whiteout_FlakesPipelineView* self, uint32_t t);
/* Render the scene seen through @p camera into target @p t. The unit of multi-viewport rendering: call once per (camera, target) pair in a frame, then Present the windowed targets. Cameras come from the scene's camera set (`Renderer::CreateCamera`). */
void whiteout_flakes_FlakesPipelineView_RenderViewport(whiteout_FlakesPipelineView* self, uint32_t t, uint32_t camera);
/* Present @p t to the window. No-op for headless targets. */
void whiteout_flakes_FlakesPipelineView_Present(whiteout_FlakesPipelineView* self, uint32_t t);
/* Tear down the gfx device. Idempotent. */
void whiteout_flakes_FlakesPipelineView_Shutdown(whiteout_FlakesPipelineView* self);
/* Last-frame stats (geoset / texture / node / particle / segment counts). */
struct whiteout_FlakesFrameStats* whiteout_flakes_FlakesPipelineView_FrameStats(const whiteout_FlakesPipelineView* self);
/* Live GPU bytes currently allocated. WebGPU backend tracks every CreateTexture / CreateBuffer and subtracts on deferred-delete drain — diagnostic for memory growth. Returns 0 on backends without tracking. */
uint64_t whiteout_flakes_FlakesPipelineView_LiveGpuBytes(const whiteout_FlakesPipelineView* self);

/* ── FlakesSceneView ─────────────────────────────────────────────── */

/* Scene-clock + content-provider surface. */
void whiteout_flakes_FlakesSceneView_delete(whiteout_FlakesSceneView* self);

/* Master animation clock the renderer ticks (ms). */
int32_t whiteout_flakes_FlakesSceneView_AnimationTimeMs(const whiteout_FlakesSceneView* self);
void whiteout_flakes_FlakesSceneView_SetAnimationTimeMs(whiteout_FlakesSceneView* self, int32_t arg);
/* Advance per-frame scene state (DNC, deferred deletes, …). */
void whiteout_flakes_FlakesSceneView_Update(whiteout_FlakesSceneView* self, float dt);
/* Point this scene's content provider at an installed Warcraft III, so archive paths resolve out of its CASC storage. */
/*  */
/* The counterpart to @ref StorageBrowser: browse an install, then hand the same root here and `LoaderView::SpawnUnit` reads the paths the browser returns. Loose files on disk keep working — CASC is consulted for what is not found beside @ref SetPE1BasePath. */
/*  */
/* No-op for scenes running on a host-supplied content provider, which resolve however the host chooses. */
void whiteout_flakes_FlakesSceneView_SetCascInstallPath(whiteout_FlakesSceneView* self, const char* root);
/* Prefer the HD (Reforged) asset chain over SD when resolving archive paths. */
/*  */
/* A CASC path exists in several mod layers; the provider tries them in order, and which order is right depends on the model. Set this from the actor's @ref ActorView::PreferredRenderMode, or textures resolve to the wrong layer and a Reforged model renders with classic art. */
void whiteout_flakes_FlakesSceneView_SetHdMode(whiteout_FlakesSceneView* self, int32_t enabled);

/* ── FlakesCameraView ─────────────────────────────────────────────── */

/* Free-orbit + scripted camera surface. */
void whiteout_flakes_FlakesCameraView_delete(whiteout_FlakesCameraView* self);

/* Re-center on the world origin in orbital mode. */
void whiteout_flakes_FlakesCameraView_Reset(whiteout_FlakesCameraView* self);
void whiteout_flakes_FlakesCameraView_SetPitch(whiteout_FlakesCameraView* self, float arg);
void whiteout_flakes_FlakesCameraView_SetYaw(whiteout_FlakesCameraView* self, float arg);
void whiteout_flakes_FlakesCameraView_SetDistance(whiteout_FlakesCameraView* self, float arg);
void whiteout_flakes_FlakesCameraView_SetTarget(whiteout_FlakesCameraView* self, float x, float y, float z);
/* Apply a mouse-drag rotation (orbital mode). */
void whiteout_flakes_FlakesCameraView_Rotate(whiteout_FlakesCameraView* self, int32_t dx, int32_t dy);
/* Apply a mouse-drag pan (orbital mode). */
void whiteout_flakes_FlakesCameraView_Pan(whiteout_FlakesCameraView* self, int32_t dx, int32_t dy);
/* Apply a wheel-step zoom. */
void whiteout_flakes_FlakesCameraView_Zoom(whiteout_FlakesCameraView* self, int32_t wheelDelta);
/* Apply a continuous-axis zoom (middle-mouse drag). */
void whiteout_flakes_FlakesCameraView_ZoomSmooth(whiteout_FlakesCameraView* self, float factor);
/* Switch from `Direct` back to `Orbital`. */
void whiteout_flakes_FlakesCameraView_SetOrbitalMode(whiteout_FlakesCameraView* self);
/* Diagonal field of view (radians). */
void whiteout_flakes_FlakesCameraView_SetFovDiagonal(whiteout_FlakesCameraView* self, float arg);
/* Near + far clip planes. */
void whiteout_flakes_FlakesCameraView_SetClip(whiteout_FlakesCameraView* self, float nz, float fz);
int32_t whiteout_flakes_FlakesCameraView_Mode(const whiteout_FlakesCameraView* self);
float whiteout_flakes_FlakesCameraView_Distance(const whiteout_FlakesCameraView* self);

/* ── FlakesSettingsView ─────────────────────────────────────────────── */

/* Display flags, post-processing tunables, and persistent host knobs that survive across runs. */
void whiteout_flakes_FlakesSettingsView_delete(whiteout_FlakesSettingsView* self);

struct whiteout_FlakesDisplayFlags* whiteout_flakes_FlakesSettingsView_DisplayFlags(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetDisplayFlags(whiteout_FlakesSettingsView* self, struct whiteout_FlakesDisplayFlags* arg);
/* Returns `true` once (then resets) whenever the render mode was changed since the last call. Hosts gate model re-spawn / material refresh on this. */
int32_t whiteout_flakes_FlakesSettingsView_ConsumeRenderModeDirty(whiteout_FlakesSettingsView* self);
int32_t whiteout_flakes_FlakesSettingsView_LightingMode(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetLightingMode(whiteout_FlakesSettingsView* self, int32_t arg);
/* Background colour as packed 0x00BBGGRR. */
uint32_t whiteout_flakes_FlakesSettingsView_BackgroundColorRaw(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetBackgroundColor(whiteout_FlakesSettingsView* self, uint8_t r, uint8_t g, uint8_t b);
float whiteout_flakes_FlakesSettingsView_TonemapExposure(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetTonemapExposure(whiteout_FlakesSettingsView* self, float arg);
/* HD-only bloom master switch. Off in SD, and inert if the backend has no bloom shader bundle. */
int32_t whiteout_flakes_FlakesSettingsView_BloomEnabled(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetBloomEnabled(whiteout_FlakesSettingsView* self, int32_t arg);
int32_t whiteout_flakes_FlakesSettingsView_IblMode(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetIblMode(whiteout_FlakesSettingsView* self, int32_t arg);
/* HD-shader debug mode (0 = off, 1..7 = visualisations). */
int32_t whiteout_flakes_FlakesSettingsView_HdDebugMode(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetHdDebugMode(whiteout_FlakesSettingsView* self, int32_t arg);
/* GTAO quality preset (0 = Low, 1 = Medium, 2 = High). */
uint32_t whiteout_flakes_FlakesSettingsView_AoQuality(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetAoQuality(whiteout_FlakesSettingsView* self, uint32_t arg);
/* LOD override (`-1` = auto-pick by screen size, `0..3` = forced). */
int32_t whiteout_flakes_FlakesSettingsView_LodOverride(const whiteout_FlakesSettingsView* self);
void whiteout_flakes_FlakesSettingsView_SetLodOverride(whiteout_FlakesSettingsView* self, int32_t arg);
void whiteout_flakes_FlakesSettingsView_SetRenderMode(whiteout_FlakesSettingsView* self, int32_t arg);

/* ── FlakesLoaderView ─────────────────────────────────────────────── */

/* Spawn / refresh / clear actors. */
void whiteout_flakes_FlakesLoaderView_delete(whiteout_FlakesLoaderView* self);

/* Spawn an actor from a path resolvable by the content provider. @return New actor handle, or `0` on failure. */
uint32_t whiteout_flakes_FlakesLoaderView_SpawnUnit(whiteout_FlakesLoaderView* self, const char* path);
/* Spawn a standalone corn effect (`.pkb` / `.pkfx`) as its own actor, with no model around it. */
/*  */
/* A corn effect is normally reached through a model: an MDX's `CORN` chunk names the `.pkb` and the loader stages an emitter for it. This plays one on its own — the same thing the viewer does when you open a `.pkb` directly. */
/*  */
/* Equivalent to `SpawnUnitFromSource` with the library's `CornEffectSource`, and exists because bindings cannot implement @ref IModelSource themselves. The actor carries a single always-on emitter and one looping placeholder sequence to keep it ticking; the effect's own runtime decides whether it loops or plays once. */
/*  */
/* @param path Resolvable by the content provider, exactly like @ref SpawnUnit. */
uint32_t whiteout_flakes_FlakesLoaderView_SpawnEffect(whiteout_FlakesLoaderView* self, const char* path);
/* Defer-destroy every actor currently in the scene. */
void whiteout_flakes_FlakesLoaderView_RequestClearAll(whiteout_FlakesLoaderView* self);
/* Destroy a single actor by handle. Used by JS wrappers that expose mdx-m3-viewer-style `instance.detach()` / `instance.hide()` semantics. */
void whiteout_flakes_FlakesLoaderView_Destroy(whiteout_FlakesLoaderView* self, uint32_t handle);

/* ── FlakesAssetsView ─────────────────────────────────────────────── */

/* Push-based asset registry view. */
/*  */
/* Renderer subsystems call into `AssetManager` directly to Acquire slots; the host uses this view to: * pump the needs queue (paths the renderer wants the host to fetch), * push fetched bytes back in via `ApplyAsset`. */
/*  */
/* Stays valid for the renderer's lifetime; cheap to copy. */
void whiteout_flakes_FlakesAssetsView_delete(whiteout_FlakesAssetsView* self);

struct whiteout_FlakesAssetsViewStats* whiteout_flakes_FlakesAssetsView_Stats(const whiteout_FlakesAssetsView* self);
/* Acquire slots for every SPL/UBR texture and SPN child-model referenced by the loaded event-data SLKs. The slots are held by the event-data cache for the rest of the session, so the host pump fetches them eagerly and they survive animation changes. Call after `LoadEventDataFiles` finishes populating the splat tables. */
void whiteout_flakes_FlakesAssetsView_PrefetchEventAssets(whiteout_FlakesAssetsView* self);
/* Per-actor variant — only Acquire slots for the SPL/UBR/SPN/FPT events the actor's template actually references. Use this instead of `PrefetchEventAssets()` on backends where every Acquire costs a network fetch (web viewer hitting Hive's CASC mirror); the global variant would pull in every entry in the SLK tables regardless of whether the loaded model fires them. */
void whiteout_flakes_FlakesAssetsView_PrefetchEventAssetsForActor(whiteout_FlakesAssetsView* self, uint32_t actor);

/* ── FlakesAssetsViewStats ─────────────────────────────────────────────── */

/* Snapshot diagnostic counters. */
whiteout_FlakesAssetsViewStats* whiteout_flakes_FlakesAssetsViewStats_new(void);
void whiteout_flakes_FlakesAssetsViewStats_delete(whiteout_FlakesAssetsViewStats* self);

uint64_t whiteout_flakes_FlakesAssetsViewStats_get_liveSlots(const whiteout_FlakesAssetsViewStats* self);
void whiteout_flakes_FlakesAssetsViewStats_set_liveSlots(whiteout_FlakesAssetsViewStats* self, uint64_t value);
uint64_t whiteout_flakes_FlakesAssetsViewStats_get_loadedSlots(const whiteout_FlakesAssetsViewStats* self);
void whiteout_flakes_FlakesAssetsViewStats_set_loadedSlots(whiteout_FlakesAssetsViewStats* self, uint64_t value);
uint64_t whiteout_flakes_FlakesAssetsViewStats_get_pendingNeeds(const whiteout_FlakesAssetsViewStats* self);
void whiteout_flakes_FlakesAssetsViewStats_set_pendingNeeds(whiteout_FlakesAssetsViewStats* self, uint64_t value);
uint64_t whiteout_flakes_FlakesAssetsViewStats_get_totalAcquires(const whiteout_FlakesAssetsViewStats* self);
void whiteout_flakes_FlakesAssetsViewStats_set_totalAcquires(whiteout_FlakesAssetsViewStats* self, uint64_t value);
uint64_t whiteout_flakes_FlakesAssetsViewStats_get_totalReleases(const whiteout_FlakesAssetsViewStats* self);
void whiteout_flakes_FlakesAssetsViewStats_set_totalReleases(whiteout_FlakesAssetsViewStats* self, uint64_t value);
uint64_t whiteout_flakes_FlakesAssetsViewStats_get_totalApplies(const whiteout_FlakesAssetsViewStats* self);
void whiteout_flakes_FlakesAssetsViewStats_set_totalApplies(whiteout_FlakesAssetsViewStats* self, uint64_t value);
uint64_t whiteout_flakes_FlakesAssetsViewStats_get_totalApplyMisses(const whiteout_FlakesAssetsViewStats* self);
void whiteout_flakes_FlakesAssetsViewStats_set_totalApplyMisses(whiteout_FlakesAssetsViewStats* self, uint64_t value);

/* ── FlakesDncView ─────────────────────────────────────────────── */

/* Day-night-cycle service. */
void whiteout_flakes_FlakesDncView_delete(whiteout_FlakesDncView* self);

/* `true` once the host has set a unit-MDL path and the DNC service has loaded successfully. */
int32_t whiteout_flakes_FlakesDncView_IsValid(const whiteout_FlakesDncView* self);
/* Time of day in hours (0..@ref GetHoursPerDay). */
float whiteout_flakes_FlakesDncView_TimeOfDay(const whiteout_FlakesDncView* self);
void whiteout_flakes_FlakesDncView_SetTimeOfDay(whiteout_FlakesDncView* self, float arg);
/* TOD playback rate (`0` = paused; `1` = real-time-equivalent). */
float whiteout_flakes_FlakesDncView_TodScale(const whiteout_FlakesDncView* self);
void whiteout_flakes_FlakesDncView_SetTodScale(whiteout_FlakesDncView* self, float arg);
/* Length of a full DNC cycle in hours (typically `24`). */
float whiteout_flakes_FlakesDncView_HoursPerDay(const whiteout_FlakesDncView* self);
/* Replace the DNC unit-MDL path (re-loads from the content provider). */
void whiteout_flakes_FlakesDncView_SetUnitMdl(whiteout_FlakesDncView* self, const char* arg);
/* Advance the DNC clock by @p dt seconds. */
void whiteout_flakes_FlakesDncView_Advance(whiteout_FlakesDncView* self, float dt);

/* ── FlakesShadowView ─────────────────────────────────────────────── */

/* Cascade-shadow-map service. */
void whiteout_flakes_FlakesShadowView_delete(whiteout_FlakesShadowView* self);

int32_t whiteout_flakes_FlakesShadowView_IsValid(const whiteout_FlakesShadowView* self);
int32_t whiteout_flakes_FlakesShadowView_IsEnabled(const whiteout_FlakesShadowView* self);
void whiteout_flakes_FlakesShadowView_SetEnabled(whiteout_FlakesShadowView* self, int32_t on);
struct whiteout_FlakesShadowParams* whiteout_flakes_FlakesShadowView_Params(const whiteout_FlakesShadowView* self);
void whiteout_flakes_FlakesShadowView_SetParams(whiteout_FlakesShadowView* self, struct whiteout_FlakesShadowParams* arg);

/* ── FlakesSplatView ─────────────────────────────────────────────── */

/* Splat-decal service (engine-spawned SPL/UBR events). */
void whiteout_flakes_FlakesSplatView_delete(whiteout_FlakesSplatView* self);

/* Remove every live splat. Hosts call this on sequence change to avoid carrying decay-only splats across cuts. */
void whiteout_flakes_FlakesSplatView_Clear(whiteout_FlakesSplatView* self);

/* ── FlakesReplaceablesView ─────────────────────────────────────────────── */

/* Replaceable-texture / tileset switching. */
void whiteout_flakes_FlakesReplaceablesView_delete(whiteout_FlakesReplaceablesView* self);

/* Returns `true` once when the tileset has changed since last call (hosts use this to invalidate cached swatches). */
int32_t whiteout_flakes_FlakesReplaceablesView_ConsumeDirty(whiteout_FlakesReplaceablesView* self);
/* Switch the active tileset; in-scene replaceables re-resolve on the next frame. */
void whiteout_flakes_FlakesReplaceablesView_SetTileset(whiteout_FlakesReplaceablesView* self, int32_t arg);

/* ── FlakesPlaybackView ─────────────────────────────────────────────── */

/* Transport controls for the scene clock — one switch that governs model animation and every effect system alike. */
/*  */
/* A frame advances in two halves: `SceneView::Update` moves the animation clocks, `Renderer::Tick` moves the particle, PE1, ribbon and corn effects simulations. Both read the state set here, so a host cannot pause one and leave the other running. */
/*  */
/* @code r.Playback().Pause();     // freeze mid-animation, particles hang in air r.Playback().Play();      // carry on from that instant r.Playback().Restart();   // rewind to the top and play r.Playback().Stop();      // rewind to the top and hold @endcode */
void whiteout_flakes_FlakesPlaybackView_delete(whiteout_FlakesPlaybackView* self);

/* Current transport state. */
int32_t whiteout_flakes_FlakesPlaybackView_State(const whiteout_FlakesPlaybackView* self);
/* Set the transport state directly. Entering @ref PlaybackState::Stopped rewinds; the other transitions do not. */
void whiteout_flakes_FlakesPlaybackView_SetState(whiteout_FlakesPlaybackView* self, int32_t arg);
/* Resume (or continue) advancing time. */
void whiteout_flakes_FlakesPlaybackView_Play(whiteout_FlakesPlaybackView* self);
/* Hold time at the current instant. Resuming continues from here. */
void whiteout_flakes_FlakesPlaybackView_Pause(whiteout_FlakesPlaybackView* self);
/* Rewind to the start and hold. Animation cursors return to zero and transient effect state — live particles, ribbon trails, PE1 instances, corn effects runtimes — is discarded, so nothing is left hanging in mid-air. */
void whiteout_flakes_FlakesPlaybackView_Stop(whiteout_FlakesPlaybackView* self);
/* Rewind to the start and play. Equivalent to `Stop()` then `Play()`, and the usual way to replay a one-shot effect. */
void whiteout_flakes_FlakesPlaybackView_Restart(whiteout_FlakesPlaybackView* self);
/* Drop transient effect state so the effect systems replay from the cursor's current position. */
/*  */
/* For hosts that move the clock themselves — a timeline scrub — rather than through this view. Particles, ribbons and corn effects are forward simulations with no seek: jumping the animation cursor leaves them mid-flight from wherever they were, which reads as the effects ignoring the scrub. This restarts them. The clock is untouched. */
void whiteout_flakes_FlakesPlaybackView_ResyncEffects(whiteout_FlakesPlaybackView* self);
/* `true` when time is not advancing (paused *or* stopped). */
int32_t whiteout_flakes_FlakesPlaybackView_IsPaused(const whiteout_FlakesPlaybackView* self);
/* Multiplier applied to every advancing frame. Survives a pause/resume, so slow-motion is not lost on Play(). */
float whiteout_flakes_FlakesPlaybackView_TimeScale(const whiteout_FlakesPlaybackView* self);
void whiteout_flakes_FlakesPlaybackView_SetTimeScale(whiteout_FlakesPlaybackView* self, float arg);

/* ── FlakesActorView ─────────────────────────────────────────────── */

/* Value-typed view onto one actor. */
/*  */
/* Constructed by `Renderer::Actor(handle)`. Cheap to copy; under the hood it's just `{ RendererImpl*, ActorHandle }`. Lifetime mirrors the renderer's — copies become invalid when the actor is removed. */
void whiteout_flakes_FlakesActorView_delete(whiteout_FlakesActorView* self);

/* `true` if the underlying actor still exists in the scene. */
int32_t whiteout_flakes_FlakesActorView_IsValid(const whiteout_FlakesActorView* self);
/* The handle this view was constructed with. */
uint32_t whiteout_flakes_FlakesActorView_Handle(const whiteout_FlakesActorView* self);
/* Role assigned at spawn time (see @ref ActorRole). */
int32_t whiteout_flakes_FlakesActorView_Role(const whiteout_FlakesActorView* self);
/* Animation playback rate (`1.0` = nominal). */
float whiteout_flakes_FlakesActorView_PlaybackSpeed(const whiteout_FlakesActorView* self);
void whiteout_flakes_FlakesActorView_SetPlaybackSpeed(whiteout_FlakesActorView* self, float arg);
/* If `true`, non-looping sequences hold their last frame instead of restarting from the beginning. */
int32_t whiteout_flakes_FlakesActorView_IgnoreNonLooping(const whiteout_FlakesActorView* self);
void whiteout_flakes_FlakesActorView_SetIgnoreNonLooping(whiteout_FlakesActorView* self, int32_t arg);
/* Packed 0x00BBGGRR team colour (low 24 bits used). */
uint32_t whiteout_flakes_FlakesActorView_TeamColor(const whiteout_FlakesActorView* self);
/* Set the team colour from sRGB byte components. */
void whiteout_flakes_FlakesActorView_SetTeamColor(whiteout_FlakesActorView* self, uint8_t r, uint8_t g, uint8_t b);
/* Mark this actor as host-driven so `Renderer::Tick` skips evaluating it. Used by the Max plugin, which receives time scrubs from Max's timeline and evaluates manually via @ref EvaluateAndApply. */
void whiteout_flakes_FlakesActorView_SetRoleExternal(whiteout_FlakesActorView* self);
/* @name Animation cursor @{ */
struct whiteout_SequenceInfoList* whiteout_flakes_FlakesActorView_Sequences(const whiteout_FlakesActorView* self);
int32_t whiteout_flakes_FlakesActorView_ActiveSequenceIndex(const whiteout_FlakesActorView* self);
void whiteout_flakes_FlakesActorView_SetActiveSequence(whiteout_FlakesActorView* self, int32_t arg);
int32_t whiteout_flakes_FlakesActorView_AnimationTimeMs(const whiteout_FlakesActorView* self);
void whiteout_flakes_FlakesActorView_SetAnimationTimeMs(whiteout_FlakesActorView* self, int32_t arg);
/* `true` once the actor has an `IAnimationSource` bound (i.e. spawn-from-source completed successfully). */
int32_t whiteout_flakes_FlakesActorView_HasAnimationSource(const whiteout_FlakesActorView* self);
/* Evaluate the animation at the actor's current cursor and push the result into the renderer state. */
/*  */
/* Used by host-driven actors (Max-plugin timeline scrub). Call `SetAnimationTimeMs(t)` first if you want a specific time. */
void whiteout_flakes_FlakesActorView_EvaluateAndApply(whiteout_FlakesActorView* self);
/* Convenience: `SetAnimationTimeMs(t)` + `EvaluateAndApply()`. */
void whiteout_flakes_FlakesActorView_EvaluateAt(whiteout_FlakesActorView* self, int32_t timeMs);
/* @name Read-only counts for status displays. @{ */
int32_t whiteout_flakes_FlakesActorView_GeosetCount(const whiteout_FlakesActorView* self);
int32_t whiteout_flakes_FlakesActorView_MaterialCount(const whiteout_FlakesActorView* self);
int32_t whiteout_flakes_FlakesActorView_CollisionShapeCount(const whiteout_FlakesActorView* self);
/* Camera presets attached to this actor's source model. */
struct whiteout_CameraPresetList* whiteout_flakes_FlakesActorView_CameraPresets(const whiteout_FlakesActorView* self);
/* Render mode the actor's template expects (`HD` if any material layer uses a non-zero BLS shaderId, else `SD`). Hosts call this after `SpawnUnit` and forward to `SettingsView::SetRenderMode` so SD models don't render through the HD pipeline (which mis-blends multi-layer SD materials) and vice-versa. */
int32_t whiteout_flakes_FlakesActorView_PreferredRenderMode(const whiteout_FlakesActorView* self);
/* Every child-model path this actor's template will eventually need: attachment slots (`AttachmentConfig`) and legacy PE1 particle emitters (`PE1EmitterConfig`). Hosts running an async loader (web build) use this to eagerly prefetch the child MDX bytes so the first attachment spawn / first PE1 fire lands in a primed cache rather than triggering a miss. */
size_t whiteout_flakes_FlakesActorView_ChildModelPaths_count(const whiteout_FlakesActorView* self);
whiteout_CString whiteout_flakes_FlakesActorView_ChildModelPaths_at(const whiteout_FlakesActorView* self, size_t index);
/* Materialises the whole list in one call. Prefer this over the
 * _count/_at pair above, which re-runs the query per index. */
struct whiteout_StringList* whiteout_flakes_FlakesActorView_ChildModelPaths(const whiteout_FlakesActorView* self);

/* ── FlakesRenderer ─────────────────────────────────────────────── */

/* Top-level WhiteoutFlakes renderer. */
/*  */
/* Construct one per process / per host. Holds every internal subsystem behind a stable PIMPL pointer; copies are disallowed. */
whiteout_FlakesRenderer* whiteout_flakes_FlakesRenderer_new(void);
void whiteout_flakes_FlakesRenderer_delete(whiteout_FlakesRenderer* self);

/* @name Sub-service handles Each call returns a small value-typed view; the underlying impl is shared with the owning `Renderer`. Views are cheap to copy. @{ */
struct whiteout_FlakesPipelineView* whiteout_flakes_FlakesRenderer_Pipeline(whiteout_FlakesRenderer* self);
struct whiteout_FlakesSceneView* whiteout_flakes_FlakesRenderer_Scene(whiteout_FlakesRenderer* self);
/* View onto the scene's default camera (handle 0). */
struct whiteout_FlakesCameraView* whiteout_flakes_FlakesRenderer_Camera(whiteout_FlakesRenderer* self);
/* Add a camera to the scene's set; returns its handle. Use for extra viewports onto the same scene (e.g. an editor's top/front/side/perspective layout). Pair with PipelineView::RenderViewport(target, handle). */
uint32_t whiteout_flakes_FlakesRenderer_CreateCamera(whiteout_FlakesRenderer* self);
/* View onto a specific camera in the scene's set. An out-of-range handle drives the default camera. */
struct whiteout_FlakesCameraView* whiteout_flakes_FlakesRenderer_CameraAt(whiteout_FlakesRenderer* self, uint32_t arg);
struct whiteout_FlakesSettingsView* whiteout_flakes_FlakesRenderer_Settings(whiteout_FlakesRenderer* self);
struct whiteout_FlakesLoaderView* whiteout_flakes_FlakesRenderer_Loader(whiteout_FlakesRenderer* self);
struct whiteout_FlakesDncView* whiteout_flakes_FlakesRenderer_Dnc(whiteout_FlakesRenderer* self);
struct whiteout_FlakesShadowView* whiteout_flakes_FlakesRenderer_Shadow(whiteout_FlakesRenderer* self);
struct whiteout_FlakesSplatView* whiteout_flakes_FlakesRenderer_Splats(whiteout_FlakesRenderer* self);
struct whiteout_FlakesReplaceablesView* whiteout_flakes_FlakesRenderer_Replaceables(whiteout_FlakesRenderer* self);
struct whiteout_FlakesAssetsView* whiteout_flakes_FlakesRenderer_Assets(whiteout_FlakesRenderer* self);
/* Play / pause / stop / restart the scene clock, for models and effects together. */
struct whiteout_FlakesPlaybackView* whiteout_flakes_FlakesRenderer_Playback(whiteout_FlakesRenderer* self);
/* Per-actor view. Returns an invalid view (`IsValid() == false`) for unknown handles. */
struct whiteout_FlakesActorView* whiteout_flakes_FlakesRenderer_Actor(whiteout_FlakesRenderer* self, uint32_t h);
/* Per-frame entry point. */
/*  */
/* Drives animation, attachment-graph propagation, particle / PE1 / ribbon / corn-effects simulation, splat decay, DNC advancement. Hosts that drive their own actor evaluation (e.g. the Max plugin, which receives time scrubs from the host timeline) can skip `Tick` and call @ref ActorView::EvaluateAndApply manually. @param dt Elapsed time since the last tick, in seconds. */
void whiteout_flakes_FlakesRenderer_Tick(whiteout_FlakesRenderer* self, float dt);

/* ── FlakesStorageBrowser ─────────────────────────────────────────────── */

/* Browses a CASC install, an MPQ archive, or a directory as one folder tree of model and effect files. */
/*  */
/* The Reforged TVFS encodes the mod chain with `:` and the content tree with `\` — `war3.w3mod:_hd.w3mod:units\nightelf\druid\druid.mdx`. This walks the archive once on open, keeps only the folders that lead to a `.mdx`, `.mdl`, `.pkb` or `.pkfx`, and presents them as directories you can descend into. Display paths drop the leading `war3.w3mod:` and use `\` throughout; each file leaf remembers its original archive path, which is what the renderer reads. */
/*  */
/* The browser is standalone — it opens its own handle on the archive and needs no `Renderer`. To render what you pick, point a scene at the same install and spawn the path this hands you: */
/*  */
/* @code StorageBrowser br; if (!br.OpenAuto(R"(C:\Program Files\Warcraft III)")) return br.LastError(); br.Descend("units"); const auto path = br.ChildPath(br.Files()[0]); */
/*  */
/* r.Scene().SetCascInstallPath(br.Root()); r.Loader().SpawnUnit(path); @endcode */
whiteout_FlakesStorageBrowser* whiteout_flakes_FlakesStorageBrowser_new(void);
void whiteout_flakes_FlakesStorageBrowser_delete(whiteout_FlakesStorageBrowser* self);

/* Open @p root as @p kind and build the folder tree. */
/*  */
/* For @ref StorageKind::Casc, @p root is the directory holding `.build.info` (or its `Data` subdirectory); for @ref StorageKind::Mpq, the archive file; for @ref StorageKind::Folder, the directory to walk. */
/*  */
/* Enumerating is the expensive part and happens here, once. Returns `false` on failure; @ref GetLastError says why. */
int32_t whiteout_flakes_FlakesStorageBrowser_Open(whiteout_FlakesStorageBrowser* self, const char* root, int32_t kind);
/* Work out what @p path is and open it. */
/*  */
/* A directory holding `.build.info` is a CASC install, any other directory is walked as a folder, and a file is treated as an MPQ. What a dialog wants when the user has just typed or dropped a path. */
int32_t whiteout_flakes_FlakesStorageBrowser_OpenAuto(whiteout_FlakesStorageBrowser* self, const char* path);
/* What the open storage turned out to be. */
int32_t whiteout_flakes_FlakesStorageBrowser_Kind(const whiteout_FlakesStorageBrowser* self);
/* Why the last @ref Open failed. Empty after a successful one. */
int32_t whiteout_flakes_FlakesStorageBrowser_IsOpen(const whiteout_FlakesStorageBrowser* self);
/* The root this was opened with. */
whiteout_CString whiteout_flakes_FlakesStorageBrowser_Root(const whiteout_FlakesStorageBrowser* self);
/* Message from the last failed @ref Open, or empty. */
whiteout_CString whiteout_flakes_FlakesStorageBrowser_LastError(const whiteout_FlakesStorageBrowser* self);
/* @name Navigation @{ @brief Current directory in display form (`\`-separated, empty at the root). */
whiteout_CString whiteout_flakes_FlakesStorageBrowser_CurrentPath(const whiteout_FlakesStorageBrowser* self);
/* The current path split into segments, for a breadcrumb bar. */
size_t whiteout_flakes_FlakesStorageBrowser_Breadcrumb_count(const whiteout_FlakesStorageBrowser* self);
whiteout_CString whiteout_flakes_FlakesStorageBrowser_Breadcrumb_at(const whiteout_FlakesStorageBrowser* self, size_t index);
/* Materialises the whole list in one call. Prefer this over the
 * _count/_at pair above, which re-runs the query per index. */
struct whiteout_StringList* whiteout_flakes_FlakesStorageBrowser_Breadcrumb(const whiteout_FlakesStorageBrowser* self);
/* Immediate subfolder names of the current directory. */
size_t whiteout_flakes_FlakesStorageBrowser_Folders_count(const whiteout_FlakesStorageBrowser* self);
whiteout_CString whiteout_flakes_FlakesStorageBrowser_Folders_at(const whiteout_FlakesStorageBrowser* self, size_t index);
/* Materialises the whole list in one call. Prefer this over the
 * _count/_at pair above, which re-runs the query per index. */
struct whiteout_StringList* whiteout_flakes_FlakesStorageBrowser_Folders(const whiteout_FlakesStorageBrowser* self);
/* File names directly inside the current directory, subject to @ref GetFilter. Names only — pair with @ref ChildPath to load one. */
size_t whiteout_flakes_FlakesStorageBrowser_Files_count(const whiteout_FlakesStorageBrowser* self);
whiteout_CString whiteout_flakes_FlakesStorageBrowser_Files_at(const whiteout_FlakesStorageBrowser* self, size_t index);
/* Materialises the whole list in one call. Prefer this over the
 * _count/_at pair above, which re-runs the query per index. */
struct whiteout_StringList* whiteout_flakes_FlakesStorageBrowser_Files(const whiteout_FlakesStorageBrowser* self);
/* Restrict @ref Files to models, to effects, or to neither. */
/*  */
/* Filters the file list only; @ref Folders is unchanged, so a folder whose contents are all filtered out still appears and simply reads as empty. That keeps the tree stable while the filter is toggled, which is what a panel wants — hiding folders would make the shape of the archive jump around. */
/*  */
/* Costs nothing to change: the archive is walked once at @ref Open and the filter is applied per call. */
void whiteout_flakes_FlakesStorageBrowser_SetFilter(whiteout_FlakesStorageBrowser* self, int32_t filter);
int32_t whiteout_flakes_FlakesStorageBrowser_Filter(const whiteout_FlakesStorageBrowser* self);
/* How many files the current directory holds in total, ignoring the filter — so a panel can say "3 of 12" rather than making an empty folder look like a dead end. */
int32_t whiteout_flakes_FlakesStorageBrowser_UnfilteredFileCount(const whiteout_FlakesStorageBrowser* self);
/* Descend into a subfolder of the current directory. No-op for a name that is not in @ref Folders. */
void whiteout_flakes_FlakesStorageBrowser_Descend(whiteout_FlakesStorageBrowser* self, const char* folderName);
/* Go up one level. No-op at the root. */
void whiteout_flakes_FlakesStorageBrowser_Ascend(whiteout_FlakesStorageBrowser* self);
/* Jump to a display path, as returned by @ref GetCurrentPath. */
void whiteout_flakes_FlakesStorageBrowser_NavigateTo(whiteout_FlakesStorageBrowser* self, const char* displayPath);
/* The original archive path of a file in the current directory — what `LoaderView::SpawnUnit` / `SpawnEffect` reads. Empty for a name that is not in @ref Files. */
whiteout_CString whiteout_flakes_FlakesStorageBrowser_ChildPath(const whiteout_FlakesStorageBrowser* self, const char* fileName);
/* `true` if @p fileName is an effect (`.pkb` / `.pkfx`) rather than a model, so a host knows which spawn call to make. */
int32_t whiteout_flakes_FlakesStorageBrowser_IsEffect(const whiteout_FlakesStorageBrowser* self, const char* fileName);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* WHITEOUT_FLAKES_H */
